// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// ActionsGetReader is a Reader for the ActionsGet structure.
type ActionsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActionsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewActionsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewActionsGetOK creates a ActionsGetOK with default headers values
func NewActionsGetOK() *ActionsGetOK {
	return &ActionsGetOK{}
}

/*ActionsGetOK handles this case with default header values.

Success
*/
type ActionsGetOK struct {
	Payload models.Action
}

func (o *ActionsGetOK) Error() string {
	return fmt.Sprintf("[GET /actions/{action_id}][%d] actionsGetOK  %+v", 200, o.Payload)
}

func (o *ActionsGetOK) GetPayload() models.Action {
	return o.Payload
}

func (o *ActionsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload as interface type
	payload, err := models.UnmarshalAction(response.Body(), consumer)
	if err != nil {
		return err
	}
	o.Payload = payload

	return nil
}
