// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// ActionsSetReader is a Reader for the ActionsSet structure.
type ActionsSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActionsSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewActionsSetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewActionsSetOK creates a ActionsSetOK with default headers values
func NewActionsSetOK() *ActionsSetOK {
	return &ActionsSetOK{}
}

/*ActionsSetOK handles this case with default header values.

Success
*/
type ActionsSetOK struct {
	Payload models.Action
}

func (o *ActionsSetOK) Error() string {
	return fmt.Sprintf("[PUT /actions/{action_id}][%d] actionsSetOK  %+v", 200, o.Payload)
}

func (o *ActionsSetOK) GetPayload() models.Action {
	return o.Payload
}

func (o *ActionsSetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload as interface type
	payload, err := models.UnmarshalAction(response.Body(), consumer)
	if err != nil {
		return err
	}
	o.Payload = payload

	return nil
}
