// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewActionsListParams creates a new ActionsListParams object
// with the default values initialized.
func NewActionsListParams() *ActionsListParams {

	return &ActionsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewActionsListParamsWithTimeout creates a new ActionsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewActionsListParamsWithTimeout(timeout time.Duration) *ActionsListParams {

	return &ActionsListParams{

		timeout: timeout,
	}
}

// NewActionsListParamsWithContext creates a new ActionsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewActionsListParamsWithContext(ctx context.Context) *ActionsListParams {

	return &ActionsListParams{

		Context: ctx,
	}
}

// NewActionsListParamsWithHTTPClient creates a new ActionsListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewActionsListParamsWithHTTPClient(client *http.Client) *ActionsListParams {

	return &ActionsListParams{
		HTTPClient: client,
	}
}

/*ActionsListParams contains all the parameters to send to the API endpoint
for the actions list operation typically these are written to a http.Request
*/
type ActionsListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the actions list params
func (o *ActionsListParams) WithTimeout(timeout time.Duration) *ActionsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the actions list params
func (o *ActionsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the actions list params
func (o *ActionsListParams) WithContext(ctx context.Context) *ActionsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the actions list params
func (o *ActionsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the actions list params
func (o *ActionsListParams) WithHTTPClient(client *http.Client) *ActionsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the actions list params
func (o *ActionsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ActionsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
