// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAPITokensListParams creates a new APITokensListParams object
// with the default values initialized.
func NewAPITokensListParams() *APITokensListParams {

	return &APITokensListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPITokensListParamsWithTimeout creates a new APITokensListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPITokensListParamsWithTimeout(timeout time.Duration) *APITokensListParams {

	return &APITokensListParams{

		timeout: timeout,
	}
}

// NewAPITokensListParamsWithContext creates a new APITokensListParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPITokensListParamsWithContext(ctx context.Context) *APITokensListParams {

	return &APITokensListParams{

		Context: ctx,
	}
}

// NewAPITokensListParamsWithHTTPClient creates a new APITokensListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPITokensListParamsWithHTTPClient(client *http.Client) *APITokensListParams {

	return &APITokensListParams{
		HTTPClient: client,
	}
}

/*APITokensListParams contains all the parameters to send to the API endpoint
for the Api tokens list operation typically these are written to a http.Request
*/
type APITokensListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api tokens list params
func (o *APITokensListParams) WithTimeout(timeout time.Duration) *APITokensListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api tokens list params
func (o *APITokensListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api tokens list params
func (o *APITokensListParams) WithContext(ctx context.Context) *APITokensListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api tokens list params
func (o *APITokensListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api tokens list params
func (o *APITokensListParams) WithHTTPClient(client *http.Client) *APITokensListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api tokens list params
func (o *APITokensListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *APITokensListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
