// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// APITokensGetReader is a Reader for the APITokensGet structure.
type APITokensGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APITokensGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAPITokensGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAPITokensGetOK creates a APITokensGetOK with default headers values
func NewAPITokensGetOK() *APITokensGetOK {
	return &APITokensGetOK{}
}

/*APITokensGetOK handles this case with default header values.

Success
*/
type APITokensGetOK struct {
	Payload *models.APIToken
}

func (o *APITokensGetOK) Error() string {
	return fmt.Sprintf("[GET /apiTokens/{token_id}][%d] apiTokensGetOK  %+v", 200, o.Payload)
}

func (o *APITokensGetOK) GetPayload() *models.APIToken {
	return o.Payload
}

func (o *APITokensGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIToken)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
