// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAPITokensGetParams creates a new APITokensGetParams object
// with the default values initialized.
func NewAPITokensGetParams() *APITokensGetParams {
	var ()
	return &APITokensGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPITokensGetParamsWithTimeout creates a new APITokensGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPITokensGetParamsWithTimeout(timeout time.Duration) *APITokensGetParams {
	var ()
	return &APITokensGetParams{

		timeout: timeout,
	}
}

// NewAPITokensGetParamsWithContext creates a new APITokensGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPITokensGetParamsWithContext(ctx context.Context) *APITokensGetParams {
	var ()
	return &APITokensGetParams{

		Context: ctx,
	}
}

// NewAPITokensGetParamsWithHTTPClient creates a new APITokensGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPITokensGetParamsWithHTTPClient(client *http.Client) *APITokensGetParams {
	var ()
	return &APITokensGetParams{
		HTTPClient: client,
	}
}

/*APITokensGetParams contains all the parameters to send to the API endpoint
for the Api tokens get operation typically these are written to a http.Request
*/
type APITokensGetParams struct {

	/*TokenID
	  Unique ID for the API token.

	*/
	TokenID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api tokens get params
func (o *APITokensGetParams) WithTimeout(timeout time.Duration) *APITokensGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api tokens get params
func (o *APITokensGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api tokens get params
func (o *APITokensGetParams) WithContext(ctx context.Context) *APITokensGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api tokens get params
func (o *APITokensGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api tokens get params
func (o *APITokensGetParams) WithHTTPClient(client *http.Client) *APITokensGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api tokens get params
func (o *APITokensGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTokenID adds the tokenID to the Api tokens get params
func (o *APITokensGetParams) WithTokenID(tokenID string) *APITokensGetParams {
	o.SetTokenID(tokenID)
	return o
}

// SetTokenID adds the tokenId to the Api tokens get params
func (o *APITokensGetParams) SetTokenID(tokenID string) {
	o.TokenID = tokenID
}

// WriteToRequest writes these params to a swagger request
func (o *APITokensGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param token_id
	if err := r.SetPathParam("token_id", o.TokenID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
