// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAPITokensRemoveParams creates a new APITokensRemoveParams object
// with the default values initialized.
func NewAPITokensRemoveParams() *APITokensRemoveParams {
	var ()
	return &APITokensRemoveParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAPITokensRemoveParamsWithTimeout creates a new APITokensRemoveParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAPITokensRemoveParamsWithTimeout(timeout time.Duration) *APITokensRemoveParams {
	var ()
	return &APITokensRemoveParams{

		timeout: timeout,
	}
}

// NewAPITokensRemoveParamsWithContext creates a new APITokensRemoveParams object
// with the default values initialized, and the ability to set a context for a request
func NewAPITokensRemoveParamsWithContext(ctx context.Context) *APITokensRemoveParams {
	var ()
	return &APITokensRemoveParams{

		Context: ctx,
	}
}

// NewAPITokensRemoveParamsWithHTTPClient creates a new APITokensRemoveParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAPITokensRemoveParamsWithHTTPClient(client *http.Client) *APITokensRemoveParams {
	var ()
	return &APITokensRemoveParams{
		HTTPClient: client,
	}
}

/*APITokensRemoveParams contains all the parameters to send to the API endpoint
for the Api tokens remove operation typically these are written to a http.Request
*/
type APITokensRemoveParams struct {

	/*TokenID
	  Unique ID for the API token.

	*/
	TokenID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Api tokens remove params
func (o *APITokensRemoveParams) WithTimeout(timeout time.Duration) *APITokensRemoveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Api tokens remove params
func (o *APITokensRemoveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Api tokens remove params
func (o *APITokensRemoveParams) WithContext(ctx context.Context) *APITokensRemoveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Api tokens remove params
func (o *APITokensRemoveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Api tokens remove params
func (o *APITokensRemoveParams) WithHTTPClient(client *http.Client) *APITokensRemoveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Api tokens remove params
func (o *APITokensRemoveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTokenID adds the tokenID to the Api tokens remove params
func (o *APITokensRemoveParams) WithTokenID(tokenID string) *APITokensRemoveParams {
	o.SetTokenID(tokenID)
	return o
}

// SetTokenID adds the tokenId to the Api tokens remove params
func (o *APITokensRemoveParams) SetTokenID(tokenID string) {
	o.TokenID = tokenID
}

// WriteToRequest writes these params to a swagger request
func (o *APITokensRemoveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param token_id
	if err := r.SetPathParam("token_id", o.TokenID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
