// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// ContinuousDataExportsListReader is a Reader for the ContinuousDataExportsList structure.
type ContinuousDataExportsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContinuousDataExportsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewContinuousDataExportsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewContinuousDataExportsListOK creates a ContinuousDataExportsListOK with default headers values
func NewContinuousDataExportsListOK() *ContinuousDataExportsListOK {
	return &ContinuousDataExportsListOK{}
}

/*ContinuousDataExportsListOK handles this case with default header values.

Success
*/
type ContinuousDataExportsListOK struct {
	Payload *models.ContinuousDataExportCollection
}

func (o *ContinuousDataExportsListOK) Error() string {
	return fmt.Sprintf("[GET /continuousDataExports][%d] continuousDataExportsListOK  %+v", 200, o.Payload)
}

func (o *ContinuousDataExportsListOK) GetPayload() *models.ContinuousDataExportCollection {
	return o.Payload
}

func (o *ContinuousDataExportsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContinuousDataExportCollection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
