// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// ContinuousDataExportsGetReader is a Reader for the ContinuousDataExportsGet structure.
type ContinuousDataExportsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContinuousDataExportsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewContinuousDataExportsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewContinuousDataExportsGetOK creates a ContinuousDataExportsGetOK with default headers values
func NewContinuousDataExportsGetOK() *ContinuousDataExportsGetOK {
	return &ContinuousDataExportsGetOK{}
}

/*ContinuousDataExportsGetOK handles this case with default header values.

Success
*/
type ContinuousDataExportsGetOK struct {
	Payload *models.ContinuousDataExport
}

func (o *ContinuousDataExportsGetOK) Error() string {
	return fmt.Sprintf("[GET /continuousDataExports/{export_id}][%d] continuousDataExportsGetOK  %+v", 200, o.Payload)
}

func (o *ContinuousDataExportsGetOK) GetPayload() *models.ContinuousDataExport {
	return o.Payload
}

func (o *ContinuousDataExportsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContinuousDataExport)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
