// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ContinuousDataExportsRemoveReader is a Reader for the ContinuousDataExportsRemove structure.
type ContinuousDataExportsRemoveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContinuousDataExportsRemoveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewContinuousDataExportsRemoveNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewContinuousDataExportsRemoveNoContent creates a ContinuousDataExportsRemoveNoContent with default headers values
func NewContinuousDataExportsRemoveNoContent() *ContinuousDataExportsRemoveNoContent {
	return &ContinuousDataExportsRemoveNoContent{}
}

/*ContinuousDataExportsRemoveNoContent handles this case with default header values.

Success
*/
type ContinuousDataExportsRemoveNoContent struct {
}

func (o *ContinuousDataExportsRemoveNoContent) Error() string {
	return fmt.Sprintf("[DELETE /continuousDataExports/{export_id}][%d] continuousDataExportsRemoveNoContent ", 204)
}

func (o *ContinuousDataExportsRemoveNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
