// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// ContinuousDataExportsSetReader is a Reader for the ContinuousDataExportsSet structure.
type ContinuousDataExportsSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContinuousDataExportsSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewContinuousDataExportsSetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewContinuousDataExportsSetOK creates a ContinuousDataExportsSetOK with default headers values
func NewContinuousDataExportsSetOK() *ContinuousDataExportsSetOK {
	return &ContinuousDataExportsSetOK{}
}

/*ContinuousDataExportsSetOK handles this case with default header values.

Success
*/
type ContinuousDataExportsSetOK struct {
	Payload *models.ContinuousDataExport
}

func (o *ContinuousDataExportsSetOK) Error() string {
	return fmt.Sprintf("[PUT /continuousDataExports/{export_id}][%d] continuousDataExportsSetOK  %+v", 200, o.Payload)
}

func (o *ContinuousDataExportsSetOK) GetPayload() *models.ContinuousDataExport {
	return o.Payload
}

func (o *ContinuousDataExportsSetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContinuousDataExport)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
