// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// NewContinuousDataExportsSetParams creates a new ContinuousDataExportsSetParams object
// with the default values initialized.
func NewContinuousDataExportsSetParams() *ContinuousDataExportsSetParams {
	var ()
	return &ContinuousDataExportsSetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewContinuousDataExportsSetParamsWithTimeout creates a new ContinuousDataExportsSetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewContinuousDataExportsSetParamsWithTimeout(timeout time.Duration) *ContinuousDataExportsSetParams {
	var ()
	return &ContinuousDataExportsSetParams{

		timeout: timeout,
	}
}

// NewContinuousDataExportsSetParamsWithContext creates a new ContinuousDataExportsSetParams object
// with the default values initialized, and the ability to set a context for a request
func NewContinuousDataExportsSetParamsWithContext(ctx context.Context) *ContinuousDataExportsSetParams {
	var ()
	return &ContinuousDataExportsSetParams{

		Context: ctx,
	}
}

// NewContinuousDataExportsSetParamsWithHTTPClient creates a new ContinuousDataExportsSetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewContinuousDataExportsSetParamsWithHTTPClient(client *http.Client) *ContinuousDataExportsSetParams {
	var ()
	return &ContinuousDataExportsSetParams{
		HTTPClient: client,
	}
}

/*ContinuousDataExportsSetParams contains all the parameters to send to the API endpoint
for the continuous data exports set operation typically these are written to a http.Request
*/
type ContinuousDataExportsSetParams struct {

	/*Body
	  Data export body.

	*/
	Body *models.ContinuousDataExport
	/*ExportID
	  Unique ID for the continuous data export.

	*/
	ExportID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the continuous data exports set params
func (o *ContinuousDataExportsSetParams) WithTimeout(timeout time.Duration) *ContinuousDataExportsSetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the continuous data exports set params
func (o *ContinuousDataExportsSetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the continuous data exports set params
func (o *ContinuousDataExportsSetParams) WithContext(ctx context.Context) *ContinuousDataExportsSetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the continuous data exports set params
func (o *ContinuousDataExportsSetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the continuous data exports set params
func (o *ContinuousDataExportsSetParams) WithHTTPClient(client *http.Client) *ContinuousDataExportsSetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the continuous data exports set params
func (o *ContinuousDataExportsSetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the continuous data exports set params
func (o *ContinuousDataExportsSetParams) WithBody(body *models.ContinuousDataExport) *ContinuousDataExportsSetParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the continuous data exports set params
func (o *ContinuousDataExportsSetParams) SetBody(body *models.ContinuousDataExport) {
	o.Body = body
}

// WithExportID adds the exportID to the continuous data exports set params
func (o *ContinuousDataExportsSetParams) WithExportID(exportID string) *ContinuousDataExportsSetParams {
	o.SetExportID(exportID)
	return o
}

// SetExportID adds the exportId to the continuous data exports set params
func (o *ContinuousDataExportsSetParams) SetExportID(exportID string) {
	o.ExportID = exportID
}

// WriteToRequest writes these params to a swagger request
func (o *ContinuousDataExportsSetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param export_id
	if err := r.SetPathParam("export_id", o.ExportID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
