// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// NewDevicesSetAttestationParams creates a new DevicesSetAttestationParams object
// with the default values initialized.
func NewDevicesSetAttestationParams() *DevicesSetAttestationParams {
	var ()
	return &DevicesSetAttestationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesSetAttestationParamsWithTimeout creates a new DevicesSetAttestationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesSetAttestationParamsWithTimeout(timeout time.Duration) *DevicesSetAttestationParams {
	var ()
	return &DevicesSetAttestationParams{

		timeout: timeout,
	}
}

// NewDevicesSetAttestationParamsWithContext creates a new DevicesSetAttestationParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesSetAttestationParamsWithContext(ctx context.Context) *DevicesSetAttestationParams {
	var ()
	return &DevicesSetAttestationParams{

		Context: ctx,
	}
}

// NewDevicesSetAttestationParamsWithHTTPClient creates a new DevicesSetAttestationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesSetAttestationParamsWithHTTPClient(client *http.Client) *DevicesSetAttestationParams {
	var ()
	return &DevicesSetAttestationParams{
		HTTPClient: client,
	}
}

/*DevicesSetAttestationParams contains all the parameters to send to the API endpoint
for the devices set attestation operation typically these are written to a http.Request
*/
type DevicesSetAttestationParams struct {

	/*Body
	  Individual device attestation body.

	*/
	Body models.Attestation
	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices set attestation params
func (o *DevicesSetAttestationParams) WithTimeout(timeout time.Duration) *DevicesSetAttestationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices set attestation params
func (o *DevicesSetAttestationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices set attestation params
func (o *DevicesSetAttestationParams) WithContext(ctx context.Context) *DevicesSetAttestationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices set attestation params
func (o *DevicesSetAttestationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices set attestation params
func (o *DevicesSetAttestationParams) WithHTTPClient(client *http.Client) *DevicesSetAttestationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices set attestation params
func (o *DevicesSetAttestationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the devices set attestation params
func (o *DevicesSetAttestationParams) WithBody(body models.Attestation) *DevicesSetAttestationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the devices set attestation params
func (o *DevicesSetAttestationParams) SetBody(body models.Attestation) {
	o.Body = body
}

// WithDeviceID adds the deviceID to the devices set attestation params
func (o *DevicesSetAttestationParams) WithDeviceID(deviceID string) *DevicesSetAttestationParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices set attestation params
func (o *DevicesSetAttestationParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesSetAttestationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
