// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDevicesGetComponentTelemetryValueParams creates a new DevicesGetComponentTelemetryValueParams object
// with the default values initialized.
func NewDevicesGetComponentTelemetryValueParams() *DevicesGetComponentTelemetryValueParams {
	var ()
	return &DevicesGetComponentTelemetryValueParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesGetComponentTelemetryValueParamsWithTimeout creates a new DevicesGetComponentTelemetryValueParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesGetComponentTelemetryValueParamsWithTimeout(timeout time.Duration) *DevicesGetComponentTelemetryValueParams {
	var ()
	return &DevicesGetComponentTelemetryValueParams{

		timeout: timeout,
	}
}

// NewDevicesGetComponentTelemetryValueParamsWithContext creates a new DevicesGetComponentTelemetryValueParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesGetComponentTelemetryValueParamsWithContext(ctx context.Context) *DevicesGetComponentTelemetryValueParams {
	var ()
	return &DevicesGetComponentTelemetryValueParams{

		Context: ctx,
	}
}

// NewDevicesGetComponentTelemetryValueParamsWithHTTPClient creates a new DevicesGetComponentTelemetryValueParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesGetComponentTelemetryValueParamsWithHTTPClient(client *http.Client) *DevicesGetComponentTelemetryValueParams {
	var ()
	return &DevicesGetComponentTelemetryValueParams{
		HTTPClient: client,
	}
}

/*DevicesGetComponentTelemetryValueParams contains all the parameters to send to the API endpoint
for the devices get component telemetry value operation typically these are written to a http.Request
*/
type DevicesGetComponentTelemetryValueParams struct {

	/*ComponentName
	  Name of the device component.

	*/
	ComponentName string
	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string
	/*TelemetryName
	  Name of this device telemetry.

	*/
	TelemetryName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices get component telemetry value params
func (o *DevicesGetComponentTelemetryValueParams) WithTimeout(timeout time.Duration) *DevicesGetComponentTelemetryValueParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices get component telemetry value params
func (o *DevicesGetComponentTelemetryValueParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices get component telemetry value params
func (o *DevicesGetComponentTelemetryValueParams) WithContext(ctx context.Context) *DevicesGetComponentTelemetryValueParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices get component telemetry value params
func (o *DevicesGetComponentTelemetryValueParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices get component telemetry value params
func (o *DevicesGetComponentTelemetryValueParams) WithHTTPClient(client *http.Client) *DevicesGetComponentTelemetryValueParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices get component telemetry value params
func (o *DevicesGetComponentTelemetryValueParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithComponentName adds the componentName to the devices get component telemetry value params
func (o *DevicesGetComponentTelemetryValueParams) WithComponentName(componentName string) *DevicesGetComponentTelemetryValueParams {
	o.SetComponentName(componentName)
	return o
}

// SetComponentName adds the componentName to the devices get component telemetry value params
func (o *DevicesGetComponentTelemetryValueParams) SetComponentName(componentName string) {
	o.ComponentName = componentName
}

// WithDeviceID adds the deviceID to the devices get component telemetry value params
func (o *DevicesGetComponentTelemetryValueParams) WithDeviceID(deviceID string) *DevicesGetComponentTelemetryValueParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices get component telemetry value params
func (o *DevicesGetComponentTelemetryValueParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WithTelemetryName adds the telemetryName to the devices get component telemetry value params
func (o *DevicesGetComponentTelemetryValueParams) WithTelemetryName(telemetryName string) *DevicesGetComponentTelemetryValueParams {
	o.SetTelemetryName(telemetryName)
	return o
}

// SetTelemetryName adds the telemetryName to the devices get component telemetry value params
func (o *DevicesGetComponentTelemetryValueParams) SetTelemetryName(telemetryName string) {
	o.TelemetryName = telemetryName
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesGetComponentTelemetryValueParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param component_name
	if err := r.SetPathParam("component_name", o.ComponentName); err != nil {
		return err
	}

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	// path param telemetry_name
	if err := r.SetPathParam("telemetry_name", o.TelemetryName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
