// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeviceTemplatesGetParams creates a new DeviceTemplatesGetParams object
// with the default values initialized.
func NewDeviceTemplatesGetParams() *DeviceTemplatesGetParams {
	var ()
	return &DeviceTemplatesGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeviceTemplatesGetParamsWithTimeout creates a new DeviceTemplatesGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeviceTemplatesGetParamsWithTimeout(timeout time.Duration) *DeviceTemplatesGetParams {
	var ()
	return &DeviceTemplatesGetParams{

		timeout: timeout,
	}
}

// NewDeviceTemplatesGetParamsWithContext creates a new DeviceTemplatesGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeviceTemplatesGetParamsWithContext(ctx context.Context) *DeviceTemplatesGetParams {
	var ()
	return &DeviceTemplatesGetParams{

		Context: ctx,
	}
}

// NewDeviceTemplatesGetParamsWithHTTPClient creates a new DeviceTemplatesGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeviceTemplatesGetParamsWithHTTPClient(client *http.Client) *DeviceTemplatesGetParams {
	var ()
	return &DeviceTemplatesGetParams{
		HTTPClient: client,
	}
}

/*DeviceTemplatesGetParams contains all the parameters to send to the API endpoint
for the device templates get operation typically these are written to a http.Request
*/
type DeviceTemplatesGetParams struct {

	/*DeviceTemplateID
	  Unique ID of the device template.

	*/
	DeviceTemplateID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the device templates get params
func (o *DeviceTemplatesGetParams) WithTimeout(timeout time.Duration) *DeviceTemplatesGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the device templates get params
func (o *DeviceTemplatesGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the device templates get params
func (o *DeviceTemplatesGetParams) WithContext(ctx context.Context) *DeviceTemplatesGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the device templates get params
func (o *DeviceTemplatesGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the device templates get params
func (o *DeviceTemplatesGetParams) WithHTTPClient(client *http.Client) *DeviceTemplatesGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the device templates get params
func (o *DeviceTemplatesGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceTemplateID adds the deviceTemplateID to the device templates get params
func (o *DeviceTemplatesGetParams) WithDeviceTemplateID(deviceTemplateID string) *DeviceTemplatesGetParams {
	o.SetDeviceTemplateID(deviceTemplateID)
	return o
}

// SetDeviceTemplateID adds the deviceTemplateId to the device templates get params
func (o *DeviceTemplatesGetParams) SetDeviceTemplateID(deviceTemplateID string) {
	o.DeviceTemplateID = deviceTemplateID
}

// WriteToRequest writes these params to a swagger request
func (o *DeviceTemplatesGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param device_template_id
	if err := r.SetPathParam("device_template_id", o.DeviceTemplateID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
