// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// NewDevicesUpdateModuleComponentPropertiesParams creates a new DevicesUpdateModuleComponentPropertiesParams object
// with the default values initialized.
func NewDevicesUpdateModuleComponentPropertiesParams() *DevicesUpdateModuleComponentPropertiesParams {
	var ()
	return &DevicesUpdateModuleComponentPropertiesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesUpdateModuleComponentPropertiesParamsWithTimeout creates a new DevicesUpdateModuleComponentPropertiesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesUpdateModuleComponentPropertiesParamsWithTimeout(timeout time.Duration) *DevicesUpdateModuleComponentPropertiesParams {
	var ()
	return &DevicesUpdateModuleComponentPropertiesParams{

		timeout: timeout,
	}
}

// NewDevicesUpdateModuleComponentPropertiesParamsWithContext creates a new DevicesUpdateModuleComponentPropertiesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesUpdateModuleComponentPropertiesParamsWithContext(ctx context.Context) *DevicesUpdateModuleComponentPropertiesParams {
	var ()
	return &DevicesUpdateModuleComponentPropertiesParams{

		Context: ctx,
	}
}

// NewDevicesUpdateModuleComponentPropertiesParamsWithHTTPClient creates a new DevicesUpdateModuleComponentPropertiesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesUpdateModuleComponentPropertiesParamsWithHTTPClient(client *http.Client) *DevicesUpdateModuleComponentPropertiesParams {
	var ()
	return &DevicesUpdateModuleComponentPropertiesParams{
		HTTPClient: client,
	}
}

/*DevicesUpdateModuleComponentPropertiesParams contains all the parameters to send to the API endpoint
for the devices update module component properties operation typically these are written to a http.Request
*/
type DevicesUpdateModuleComponentPropertiesParams struct {

	/*Body
	  Module properties.

	*/
	Body models.DeviceProperties
	/*ComponentName
	  Name of the device component.

	*/
	ComponentName string
	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string
	/*ModuleName
	  Name of the device module.

	*/
	ModuleName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices update module component properties params
func (o *DevicesUpdateModuleComponentPropertiesParams) WithTimeout(timeout time.Duration) *DevicesUpdateModuleComponentPropertiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices update module component properties params
func (o *DevicesUpdateModuleComponentPropertiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices update module component properties params
func (o *DevicesUpdateModuleComponentPropertiesParams) WithContext(ctx context.Context) *DevicesUpdateModuleComponentPropertiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices update module component properties params
func (o *DevicesUpdateModuleComponentPropertiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices update module component properties params
func (o *DevicesUpdateModuleComponentPropertiesParams) WithHTTPClient(client *http.Client) *DevicesUpdateModuleComponentPropertiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices update module component properties params
func (o *DevicesUpdateModuleComponentPropertiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the devices update module component properties params
func (o *DevicesUpdateModuleComponentPropertiesParams) WithBody(body models.DeviceProperties) *DevicesUpdateModuleComponentPropertiesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the devices update module component properties params
func (o *DevicesUpdateModuleComponentPropertiesParams) SetBody(body models.DeviceProperties) {
	o.Body = body
}

// WithComponentName adds the componentName to the devices update module component properties params
func (o *DevicesUpdateModuleComponentPropertiesParams) WithComponentName(componentName string) *DevicesUpdateModuleComponentPropertiesParams {
	o.SetComponentName(componentName)
	return o
}

// SetComponentName adds the componentName to the devices update module component properties params
func (o *DevicesUpdateModuleComponentPropertiesParams) SetComponentName(componentName string) {
	o.ComponentName = componentName
}

// WithDeviceID adds the deviceID to the devices update module component properties params
func (o *DevicesUpdateModuleComponentPropertiesParams) WithDeviceID(deviceID string) *DevicesUpdateModuleComponentPropertiesParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices update module component properties params
func (o *DevicesUpdateModuleComponentPropertiesParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WithModuleName adds the moduleName to the devices update module component properties params
func (o *DevicesUpdateModuleComponentPropertiesParams) WithModuleName(moduleName string) *DevicesUpdateModuleComponentPropertiesParams {
	o.SetModuleName(moduleName)
	return o
}

// SetModuleName adds the moduleName to the devices update module component properties params
func (o *DevicesUpdateModuleComponentPropertiesParams) SetModuleName(moduleName string) {
	o.ModuleName = moduleName
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesUpdateModuleComponentPropertiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param component_name
	if err := r.SetPathParam("component_name", o.ComponentName); err != nil {
		return err
	}

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	// path param module_name
	if err := r.SetPathParam("module_name", o.ModuleName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
