// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// DevicesGetModuleComponentTelemetryValueReader is a Reader for the DevicesGetModuleComponentTelemetryValue structure.
type DevicesGetModuleComponentTelemetryValueReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DevicesGetModuleComponentTelemetryValueReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDevicesGetModuleComponentTelemetryValueOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDevicesGetModuleComponentTelemetryValueOK creates a DevicesGetModuleComponentTelemetryValueOK with default headers values
func NewDevicesGetModuleComponentTelemetryValueOK() *DevicesGetModuleComponentTelemetryValueOK {
	return &DevicesGetModuleComponentTelemetryValueOK{}
}

/*DevicesGetModuleComponentTelemetryValueOK handles this case with default header values.

Success
*/
type DevicesGetModuleComponentTelemetryValueOK struct {
	Payload *models.DeviceTelemetry
}

func (o *DevicesGetModuleComponentTelemetryValueOK) Error() string {
	return fmt.Sprintf("[GET /devices/{device_id}/modules/{module_name}/components/{component_name}/telemetry/{telemetry_name}][%d] devicesGetModuleComponentTelemetryValueOK  %+v", 200, o.Payload)
}

func (o *DevicesGetModuleComponentTelemetryValueOK) GetPayload() *models.DeviceTelemetry {
	return o.Payload
}

func (o *DevicesGetModuleComponentTelemetryValueOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceTelemetry)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
