// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeviceGroupsListParams creates a new DeviceGroupsListParams object
// with the default values initialized.
func NewDeviceGroupsListParams() *DeviceGroupsListParams {

	return &DeviceGroupsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeviceGroupsListParamsWithTimeout creates a new DeviceGroupsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeviceGroupsListParamsWithTimeout(timeout time.Duration) *DeviceGroupsListParams {

	return &DeviceGroupsListParams{

		timeout: timeout,
	}
}

// NewDeviceGroupsListParamsWithContext creates a new DeviceGroupsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeviceGroupsListParamsWithContext(ctx context.Context) *DeviceGroupsListParams {

	return &DeviceGroupsListParams{

		Context: ctx,
	}
}

// NewDeviceGroupsListParamsWithHTTPClient creates a new DeviceGroupsListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeviceGroupsListParamsWithHTTPClient(client *http.Client) *DeviceGroupsListParams {

	return &DeviceGroupsListParams{
		HTTPClient: client,
	}
}

/*DeviceGroupsListParams contains all the parameters to send to the API endpoint
for the device groups list operation typically these are written to a http.Request
*/
type DeviceGroupsListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the device groups list params
func (o *DeviceGroupsListParams) WithTimeout(timeout time.Duration) *DeviceGroupsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the device groups list params
func (o *DeviceGroupsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the device groups list params
func (o *DeviceGroupsListParams) WithContext(ctx context.Context) *DeviceGroupsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the device groups list params
func (o *DeviceGroupsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the device groups list params
func (o *DeviceGroupsListParams) WithHTTPClient(client *http.Client) *DeviceGroupsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the device groups list params
func (o *DeviceGroupsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeviceGroupsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
