// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDevicesGetModuleCommandHistoryParams creates a new DevicesGetModuleCommandHistoryParams object
// with the default values initialized.
func NewDevicesGetModuleCommandHistoryParams() *DevicesGetModuleCommandHistoryParams {
	var ()
	return &DevicesGetModuleCommandHistoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesGetModuleCommandHistoryParamsWithTimeout creates a new DevicesGetModuleCommandHistoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesGetModuleCommandHistoryParamsWithTimeout(timeout time.Duration) *DevicesGetModuleCommandHistoryParams {
	var ()
	return &DevicesGetModuleCommandHistoryParams{

		timeout: timeout,
	}
}

// NewDevicesGetModuleCommandHistoryParamsWithContext creates a new DevicesGetModuleCommandHistoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesGetModuleCommandHistoryParamsWithContext(ctx context.Context) *DevicesGetModuleCommandHistoryParams {
	var ()
	return &DevicesGetModuleCommandHistoryParams{

		Context: ctx,
	}
}

// NewDevicesGetModuleCommandHistoryParamsWithHTTPClient creates a new DevicesGetModuleCommandHistoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesGetModuleCommandHistoryParamsWithHTTPClient(client *http.Client) *DevicesGetModuleCommandHistoryParams {
	var ()
	return &DevicesGetModuleCommandHistoryParams{
		HTTPClient: client,
	}
}

/*DevicesGetModuleCommandHistoryParams contains all the parameters to send to the API endpoint
for the devices get module command history operation typically these are written to a http.Request
*/
type DevicesGetModuleCommandHistoryParams struct {

	/*CommandName
	  Name of this device command.

	*/
	CommandName string
	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string
	/*ModuleName
	  Name of the device module.

	*/
	ModuleName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices get module command history params
func (o *DevicesGetModuleCommandHistoryParams) WithTimeout(timeout time.Duration) *DevicesGetModuleCommandHistoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices get module command history params
func (o *DevicesGetModuleCommandHistoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices get module command history params
func (o *DevicesGetModuleCommandHistoryParams) WithContext(ctx context.Context) *DevicesGetModuleCommandHistoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices get module command history params
func (o *DevicesGetModuleCommandHistoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices get module command history params
func (o *DevicesGetModuleCommandHistoryParams) WithHTTPClient(client *http.Client) *DevicesGetModuleCommandHistoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices get module command history params
func (o *DevicesGetModuleCommandHistoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCommandName adds the commandName to the devices get module command history params
func (o *DevicesGetModuleCommandHistoryParams) WithCommandName(commandName string) *DevicesGetModuleCommandHistoryParams {
	o.SetCommandName(commandName)
	return o
}

// SetCommandName adds the commandName to the devices get module command history params
func (o *DevicesGetModuleCommandHistoryParams) SetCommandName(commandName string) {
	o.CommandName = commandName
}

// WithDeviceID adds the deviceID to the devices get module command history params
func (o *DevicesGetModuleCommandHistoryParams) WithDeviceID(deviceID string) *DevicesGetModuleCommandHistoryParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices get module command history params
func (o *DevicesGetModuleCommandHistoryParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WithModuleName adds the moduleName to the devices get module command history params
func (o *DevicesGetModuleCommandHistoryParams) WithModuleName(moduleName string) *DevicesGetModuleCommandHistoryParams {
	o.SetModuleName(moduleName)
	return o
}

// SetModuleName adds the moduleName to the devices get module command history params
func (o *DevicesGetModuleCommandHistoryParams) SetModuleName(moduleName string) {
	o.ModuleName = moduleName
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesGetModuleCommandHistoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param command_name
	if err := r.SetPathParam("command_name", o.CommandName); err != nil {
		return err
	}

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	// path param module_name
	if err := r.SetPathParam("module_name", o.ModuleName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
