// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// DevicesListComponentsReader is a Reader for the DevicesListComponents structure.
type DevicesListComponentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DevicesListComponentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDevicesListComponentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDevicesListComponentsOK creates a DevicesListComponentsOK with default headers values
func NewDevicesListComponentsOK() *DevicesListComponentsOK {
	return &DevicesListComponentsOK{}
}

/*DevicesListComponentsOK handles this case with default header values.

Success
*/
type DevicesListComponentsOK struct {
	Payload *models.Collection
}

func (o *DevicesListComponentsOK) Error() string {
	return fmt.Sprintf("[GET /devices/{device_id}/components][%d] devicesListComponentsOK  %+v", 200, o.Payload)
}

func (o *DevicesListComponentsOK) GetPayload() *models.Collection {
	return o.Payload
}

func (o *DevicesListComponentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Collection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
