// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDevicesRemoveParams creates a new DevicesRemoveParams object
// with the default values initialized.
func NewDevicesRemoveParams() *DevicesRemoveParams {
	var ()
	return &DevicesRemoveParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesRemoveParamsWithTimeout creates a new DevicesRemoveParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesRemoveParamsWithTimeout(timeout time.Duration) *DevicesRemoveParams {
	var ()
	return &DevicesRemoveParams{

		timeout: timeout,
	}
}

// NewDevicesRemoveParamsWithContext creates a new DevicesRemoveParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesRemoveParamsWithContext(ctx context.Context) *DevicesRemoveParams {
	var ()
	return &DevicesRemoveParams{

		Context: ctx,
	}
}

// NewDevicesRemoveParamsWithHTTPClient creates a new DevicesRemoveParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesRemoveParamsWithHTTPClient(client *http.Client) *DevicesRemoveParams {
	var ()
	return &DevicesRemoveParams{
		HTTPClient: client,
	}
}

/*DevicesRemoveParams contains all the parameters to send to the API endpoint
for the devices remove operation typically these are written to a http.Request
*/
type DevicesRemoveParams struct {

	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices remove params
func (o *DevicesRemoveParams) WithTimeout(timeout time.Duration) *DevicesRemoveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices remove params
func (o *DevicesRemoveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices remove params
func (o *DevicesRemoveParams) WithContext(ctx context.Context) *DevicesRemoveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices remove params
func (o *DevicesRemoveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices remove params
func (o *DevicesRemoveParams) WithHTTPClient(client *http.Client) *DevicesRemoveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices remove params
func (o *DevicesRemoveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the devices remove params
func (o *DevicesRemoveParams) WithDeviceID(deviceID string) *DevicesRemoveParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices remove params
func (o *DevicesRemoveParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesRemoveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
