// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// NewDevicesExecuteCommandParams creates a new DevicesExecuteCommandParams object
// with the default values initialized.
func NewDevicesExecuteCommandParams() *DevicesExecuteCommandParams {
	var ()
	return &DevicesExecuteCommandParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesExecuteCommandParamsWithTimeout creates a new DevicesExecuteCommandParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesExecuteCommandParamsWithTimeout(timeout time.Duration) *DevicesExecuteCommandParams {
	var ()
	return &DevicesExecuteCommandParams{

		timeout: timeout,
	}
}

// NewDevicesExecuteCommandParamsWithContext creates a new DevicesExecuteCommandParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesExecuteCommandParamsWithContext(ctx context.Context) *DevicesExecuteCommandParams {
	var ()
	return &DevicesExecuteCommandParams{

		Context: ctx,
	}
}

// NewDevicesExecuteCommandParamsWithHTTPClient creates a new DevicesExecuteCommandParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesExecuteCommandParamsWithHTTPClient(client *http.Client) *DevicesExecuteCommandParams {
	var ()
	return &DevicesExecuteCommandParams{
		HTTPClient: client,
	}
}

/*DevicesExecuteCommandParams contains all the parameters to send to the API endpoint
for the devices execute command operation typically these are written to a http.Request
*/
type DevicesExecuteCommandParams struct {

	/*Body
	  Device command body.

	*/
	Body *models.DeviceCommand
	/*CommandName
	  Name of this device command.

	*/
	CommandName string
	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices execute command params
func (o *DevicesExecuteCommandParams) WithTimeout(timeout time.Duration) *DevicesExecuteCommandParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices execute command params
func (o *DevicesExecuteCommandParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices execute command params
func (o *DevicesExecuteCommandParams) WithContext(ctx context.Context) *DevicesExecuteCommandParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices execute command params
func (o *DevicesExecuteCommandParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices execute command params
func (o *DevicesExecuteCommandParams) WithHTTPClient(client *http.Client) *DevicesExecuteCommandParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices execute command params
func (o *DevicesExecuteCommandParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the devices execute command params
func (o *DevicesExecuteCommandParams) WithBody(body *models.DeviceCommand) *DevicesExecuteCommandParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the devices execute command params
func (o *DevicesExecuteCommandParams) SetBody(body *models.DeviceCommand) {
	o.Body = body
}

// WithCommandName adds the commandName to the devices execute command params
func (o *DevicesExecuteCommandParams) WithCommandName(commandName string) *DevicesExecuteCommandParams {
	o.SetCommandName(commandName)
	return o
}

// SetCommandName adds the commandName to the devices execute command params
func (o *DevicesExecuteCommandParams) SetCommandName(commandName string) {
	o.CommandName = commandName
}

// WithDeviceID adds the deviceID to the devices execute command params
func (o *DevicesExecuteCommandParams) WithDeviceID(deviceID string) *DevicesExecuteCommandParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices execute command params
func (o *DevicesExecuteCommandParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesExecuteCommandParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param command_name
	if err := r.SetPathParam("command_name", o.CommandName); err != nil {
		return err
	}

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
