// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDevicesGetCommandHistoryParams creates a new DevicesGetCommandHistoryParams object
// with the default values initialized.
func NewDevicesGetCommandHistoryParams() *DevicesGetCommandHistoryParams {
	var ()
	return &DevicesGetCommandHistoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesGetCommandHistoryParamsWithTimeout creates a new DevicesGetCommandHistoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesGetCommandHistoryParamsWithTimeout(timeout time.Duration) *DevicesGetCommandHistoryParams {
	var ()
	return &DevicesGetCommandHistoryParams{

		timeout: timeout,
	}
}

// NewDevicesGetCommandHistoryParamsWithContext creates a new DevicesGetCommandHistoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesGetCommandHistoryParamsWithContext(ctx context.Context) *DevicesGetCommandHistoryParams {
	var ()
	return &DevicesGetCommandHistoryParams{

		Context: ctx,
	}
}

// NewDevicesGetCommandHistoryParamsWithHTTPClient creates a new DevicesGetCommandHistoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesGetCommandHistoryParamsWithHTTPClient(client *http.Client) *DevicesGetCommandHistoryParams {
	var ()
	return &DevicesGetCommandHistoryParams{
		HTTPClient: client,
	}
}

/*DevicesGetCommandHistoryParams contains all the parameters to send to the API endpoint
for the devices get command history operation typically these are written to a http.Request
*/
type DevicesGetCommandHistoryParams struct {

	/*CommandName
	  Name of this device command.

	*/
	CommandName string
	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices get command history params
func (o *DevicesGetCommandHistoryParams) WithTimeout(timeout time.Duration) *DevicesGetCommandHistoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices get command history params
func (o *DevicesGetCommandHistoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices get command history params
func (o *DevicesGetCommandHistoryParams) WithContext(ctx context.Context) *DevicesGetCommandHistoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices get command history params
func (o *DevicesGetCommandHistoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices get command history params
func (o *DevicesGetCommandHistoryParams) WithHTTPClient(client *http.Client) *DevicesGetCommandHistoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices get command history params
func (o *DevicesGetCommandHistoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCommandName adds the commandName to the devices get command history params
func (o *DevicesGetCommandHistoryParams) WithCommandName(commandName string) *DevicesGetCommandHistoryParams {
	o.SetCommandName(commandName)
	return o
}

// SetCommandName adds the commandName to the devices get command history params
func (o *DevicesGetCommandHistoryParams) SetCommandName(commandName string) {
	o.CommandName = commandName
}

// WithDeviceID adds the deviceID to the devices get command history params
func (o *DevicesGetCommandHistoryParams) WithDeviceID(deviceID string) *DevicesGetCommandHistoryParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices get command history params
func (o *DevicesGetCommandHistoryParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesGetCommandHistoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param command_name
	if err := r.SetPathParam("command_name", o.CommandName); err != nil {
		return err
	}

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
