// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// DevicesGetCloudPropertiesReader is a Reader for the DevicesGetCloudProperties structure.
type DevicesGetCloudPropertiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DevicesGetCloudPropertiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDevicesGetCloudPropertiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDevicesGetCloudPropertiesOK creates a DevicesGetCloudPropertiesOK with default headers values
func NewDevicesGetCloudPropertiesOK() *DevicesGetCloudPropertiesOK {
	return &DevicesGetCloudPropertiesOK{}
}

/*DevicesGetCloudPropertiesOK handles this case with default header values.

Success
*/
type DevicesGetCloudPropertiesOK struct {
	Payload models.DeviceCloudProperties
}

func (o *DevicesGetCloudPropertiesOK) Error() string {
	return fmt.Sprintf("[GET /devices/{device_id}/cloudProperties][%d] devicesGetCloudPropertiesOK  %+v", 200, o.Payload)
}

func (o *DevicesGetCloudPropertiesOK) GetPayload() models.DeviceCloudProperties {
	return o.Payload
}

func (o *DevicesGetCloudPropertiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
