// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// DeviceTemplatesListReader is a Reader for the DeviceTemplatesList structure.
type DeviceTemplatesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeviceTemplatesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeviceTemplatesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeviceTemplatesListOK creates a DeviceTemplatesListOK with default headers values
func NewDeviceTemplatesListOK() *DeviceTemplatesListOK {
	return &DeviceTemplatesListOK{}
}

/*DeviceTemplatesListOK handles this case with default header values.

Success
*/
type DeviceTemplatesListOK struct {
	Payload *models.DeviceTemplateCollection
}

func (o *DeviceTemplatesListOK) Error() string {
	return fmt.Sprintf("[GET /deviceTemplates][%d] deviceTemplatesListOK  %+v", 200, o.Payload)
}

func (o *DeviceTemplatesListOK) GetPayload() *models.DeviceTemplateCollection {
	return o.Payload
}

func (o *DeviceTemplatesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceTemplateCollection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
