// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// NewDevicesUpdateModulePropertiesParams creates a new DevicesUpdateModulePropertiesParams object
// with the default values initialized.
func NewDevicesUpdateModulePropertiesParams() *DevicesUpdateModulePropertiesParams {
	var ()
	return &DevicesUpdateModulePropertiesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesUpdateModulePropertiesParamsWithTimeout creates a new DevicesUpdateModulePropertiesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesUpdateModulePropertiesParamsWithTimeout(timeout time.Duration) *DevicesUpdateModulePropertiesParams {
	var ()
	return &DevicesUpdateModulePropertiesParams{

		timeout: timeout,
	}
}

// NewDevicesUpdateModulePropertiesParamsWithContext creates a new DevicesUpdateModulePropertiesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesUpdateModulePropertiesParamsWithContext(ctx context.Context) *DevicesUpdateModulePropertiesParams {
	var ()
	return &DevicesUpdateModulePropertiesParams{

		Context: ctx,
	}
}

// NewDevicesUpdateModulePropertiesParamsWithHTTPClient creates a new DevicesUpdateModulePropertiesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesUpdateModulePropertiesParamsWithHTTPClient(client *http.Client) *DevicesUpdateModulePropertiesParams {
	var ()
	return &DevicesUpdateModulePropertiesParams{
		HTTPClient: client,
	}
}

/*DevicesUpdateModulePropertiesParams contains all the parameters to send to the API endpoint
for the devices update module properties operation typically these are written to a http.Request
*/
type DevicesUpdateModulePropertiesParams struct {

	/*Body
	  Module properties.

	*/
	Body models.DeviceProperties
	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string
	/*ModuleName
	  Name of the device module.

	*/
	ModuleName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices update module properties params
func (o *DevicesUpdateModulePropertiesParams) WithTimeout(timeout time.Duration) *DevicesUpdateModulePropertiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices update module properties params
func (o *DevicesUpdateModulePropertiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices update module properties params
func (o *DevicesUpdateModulePropertiesParams) WithContext(ctx context.Context) *DevicesUpdateModulePropertiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices update module properties params
func (o *DevicesUpdateModulePropertiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices update module properties params
func (o *DevicesUpdateModulePropertiesParams) WithHTTPClient(client *http.Client) *DevicesUpdateModulePropertiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices update module properties params
func (o *DevicesUpdateModulePropertiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the devices update module properties params
func (o *DevicesUpdateModulePropertiesParams) WithBody(body models.DeviceProperties) *DevicesUpdateModulePropertiesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the devices update module properties params
func (o *DevicesUpdateModulePropertiesParams) SetBody(body models.DeviceProperties) {
	o.Body = body
}

// WithDeviceID adds the deviceID to the devices update module properties params
func (o *DevicesUpdateModulePropertiesParams) WithDeviceID(deviceID string) *DevicesUpdateModulePropertiesParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices update module properties params
func (o *DevicesUpdateModulePropertiesParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WithModuleName adds the moduleName to the devices update module properties params
func (o *DevicesUpdateModulePropertiesParams) WithModuleName(moduleName string) *DevicesUpdateModulePropertiesParams {
	o.SetModuleName(moduleName)
	return o
}

// SetModuleName adds the moduleName to the devices update module properties params
func (o *DevicesUpdateModulePropertiesParams) SetModuleName(moduleName string) {
	o.ModuleName = moduleName
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesUpdateModulePropertiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	// path param module_name
	if err := r.SetPathParam("module_name", o.ModuleName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
