// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDevicesGetComponentParams creates a new DevicesGetComponentParams object
// with the default values initialized.
func NewDevicesGetComponentParams() *DevicesGetComponentParams {
	var ()
	return &DevicesGetComponentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesGetComponentParamsWithTimeout creates a new DevicesGetComponentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesGetComponentParamsWithTimeout(timeout time.Duration) *DevicesGetComponentParams {
	var ()
	return &DevicesGetComponentParams{

		timeout: timeout,
	}
}

// NewDevicesGetComponentParamsWithContext creates a new DevicesGetComponentParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesGetComponentParamsWithContext(ctx context.Context) *DevicesGetComponentParams {
	var ()
	return &DevicesGetComponentParams{

		Context: ctx,
	}
}

// NewDevicesGetComponentParamsWithHTTPClient creates a new DevicesGetComponentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesGetComponentParamsWithHTTPClient(client *http.Client) *DevicesGetComponentParams {
	var ()
	return &DevicesGetComponentParams{
		HTTPClient: client,
	}
}

/*DevicesGetComponentParams contains all the parameters to send to the API endpoint
for the devices get component operation typically these are written to a http.Request
*/
type DevicesGetComponentParams struct {

	/*ComponentName
	  Name of the device component.

	*/
	ComponentName string
	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices get component params
func (o *DevicesGetComponentParams) WithTimeout(timeout time.Duration) *DevicesGetComponentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices get component params
func (o *DevicesGetComponentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices get component params
func (o *DevicesGetComponentParams) WithContext(ctx context.Context) *DevicesGetComponentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices get component params
func (o *DevicesGetComponentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices get component params
func (o *DevicesGetComponentParams) WithHTTPClient(client *http.Client) *DevicesGetComponentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices get component params
func (o *DevicesGetComponentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithComponentName adds the componentName to the devices get component params
func (o *DevicesGetComponentParams) WithComponentName(componentName string) *DevicesGetComponentParams {
	o.SetComponentName(componentName)
	return o
}

// SetComponentName adds the componentName to the devices get component params
func (o *DevicesGetComponentParams) SetComponentName(componentName string) {
	o.ComponentName = componentName
}

// WithDeviceID adds the deviceID to the devices get component params
func (o *DevicesGetComponentParams) WithDeviceID(deviceID string) *DevicesGetComponentParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices get component params
func (o *DevicesGetComponentParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesGetComponentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param component_name
	if err := r.SetPathParam("component_name", o.ComponentName); err != nil {
		return err
	}

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
