// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDevicesGetCloudPropertiesParams creates a new DevicesGetCloudPropertiesParams object
// with the default values initialized.
func NewDevicesGetCloudPropertiesParams() *DevicesGetCloudPropertiesParams {
	var ()
	return &DevicesGetCloudPropertiesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesGetCloudPropertiesParamsWithTimeout creates a new DevicesGetCloudPropertiesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesGetCloudPropertiesParamsWithTimeout(timeout time.Duration) *DevicesGetCloudPropertiesParams {
	var ()
	return &DevicesGetCloudPropertiesParams{

		timeout: timeout,
	}
}

// NewDevicesGetCloudPropertiesParamsWithContext creates a new DevicesGetCloudPropertiesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesGetCloudPropertiesParamsWithContext(ctx context.Context) *DevicesGetCloudPropertiesParams {
	var ()
	return &DevicesGetCloudPropertiesParams{

		Context: ctx,
	}
}

// NewDevicesGetCloudPropertiesParamsWithHTTPClient creates a new DevicesGetCloudPropertiesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesGetCloudPropertiesParamsWithHTTPClient(client *http.Client) *DevicesGetCloudPropertiesParams {
	var ()
	return &DevicesGetCloudPropertiesParams{
		HTTPClient: client,
	}
}

/*DevicesGetCloudPropertiesParams contains all the parameters to send to the API endpoint
for the devices get cloud properties operation typically these are written to a http.Request
*/
type DevicesGetCloudPropertiesParams struct {

	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices get cloud properties params
func (o *DevicesGetCloudPropertiesParams) WithTimeout(timeout time.Duration) *DevicesGetCloudPropertiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices get cloud properties params
func (o *DevicesGetCloudPropertiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices get cloud properties params
func (o *DevicesGetCloudPropertiesParams) WithContext(ctx context.Context) *DevicesGetCloudPropertiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices get cloud properties params
func (o *DevicesGetCloudPropertiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices get cloud properties params
func (o *DevicesGetCloudPropertiesParams) WithHTTPClient(client *http.Client) *DevicesGetCloudPropertiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices get cloud properties params
func (o *DevicesGetCloudPropertiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the devices get cloud properties params
func (o *DevicesGetCloudPropertiesParams) WithDeviceID(deviceID string) *DevicesGetCloudPropertiesParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices get cloud properties params
func (o *DevicesGetCloudPropertiesParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesGetCloudPropertiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
