// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// DeviceTemplatesSetReader is a Reader for the DeviceTemplatesSet structure.
type DeviceTemplatesSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeviceTemplatesSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeviceTemplatesSetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeviceTemplatesSetOK creates a DeviceTemplatesSetOK with default headers values
func NewDeviceTemplatesSetOK() *DeviceTemplatesSetOK {
	return &DeviceTemplatesSetOK{}
}

/*DeviceTemplatesSetOK handles this case with default header values.

Success
*/
type DeviceTemplatesSetOK struct {
	Payload *models.DeviceTemplate
}

func (o *DeviceTemplatesSetOK) Error() string {
	return fmt.Sprintf("[PUT /deviceTemplates/{device_template_id}][%d] deviceTemplatesSetOK  %+v", 200, o.Payload)
}

func (o *DeviceTemplatesSetOK) GetPayload() *models.DeviceTemplate {
	return o.Payload
}

func (o *DeviceTemplatesSetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceTemplate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
