// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// DeviceTemplatesGetMergedReader is a Reader for the DeviceTemplatesGetMerged structure.
type DeviceTemplatesGetMergedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeviceTemplatesGetMergedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeviceTemplatesGetMergedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeviceTemplatesGetMergedOK creates a DeviceTemplatesGetMergedOK with default headers values
func NewDeviceTemplatesGetMergedOK() *DeviceTemplatesGetMergedOK {
	return &DeviceTemplatesGetMergedOK{}
}

/*DeviceTemplatesGetMergedOK handles this case with default header values.

Success
*/
type DeviceTemplatesGetMergedOK struct {
	Payload *models.DeviceTemplate
}

func (o *DeviceTemplatesGetMergedOK) Error() string {
	return fmt.Sprintf("[GET /deviceTemplates/{device_template_id}/merged][%d] deviceTemplatesGetMergedOK  %+v", 200, o.Payload)
}

func (o *DeviceTemplatesGetMergedOK) GetPayload() *models.DeviceTemplate {
	return o.Payload
}

func (o *DeviceTemplatesGetMergedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceTemplate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
