// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDevicesRemoveAttestationParams creates a new DevicesRemoveAttestationParams object
// with the default values initialized.
func NewDevicesRemoveAttestationParams() *DevicesRemoveAttestationParams {
	var ()
	return &DevicesRemoveAttestationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesRemoveAttestationParamsWithTimeout creates a new DevicesRemoveAttestationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesRemoveAttestationParamsWithTimeout(timeout time.Duration) *DevicesRemoveAttestationParams {
	var ()
	return &DevicesRemoveAttestationParams{

		timeout: timeout,
	}
}

// NewDevicesRemoveAttestationParamsWithContext creates a new DevicesRemoveAttestationParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesRemoveAttestationParamsWithContext(ctx context.Context) *DevicesRemoveAttestationParams {
	var ()
	return &DevicesRemoveAttestationParams{

		Context: ctx,
	}
}

// NewDevicesRemoveAttestationParamsWithHTTPClient creates a new DevicesRemoveAttestationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesRemoveAttestationParamsWithHTTPClient(client *http.Client) *DevicesRemoveAttestationParams {
	var ()
	return &DevicesRemoveAttestationParams{
		HTTPClient: client,
	}
}

/*DevicesRemoveAttestationParams contains all the parameters to send to the API endpoint
for the devices remove attestation operation typically these are written to a http.Request
*/
type DevicesRemoveAttestationParams struct {

	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices remove attestation params
func (o *DevicesRemoveAttestationParams) WithTimeout(timeout time.Duration) *DevicesRemoveAttestationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices remove attestation params
func (o *DevicesRemoveAttestationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices remove attestation params
func (o *DevicesRemoveAttestationParams) WithContext(ctx context.Context) *DevicesRemoveAttestationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices remove attestation params
func (o *DevicesRemoveAttestationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices remove attestation params
func (o *DevicesRemoveAttestationParams) WithHTTPClient(client *http.Client) *DevicesRemoveAttestationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices remove attestation params
func (o *DevicesRemoveAttestationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the devices remove attestation params
func (o *DevicesRemoveAttestationParams) WithDeviceID(deviceID string) *DevicesRemoveAttestationParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices remove attestation params
func (o *DevicesRemoveAttestationParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesRemoveAttestationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
