// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// DeviceGroupsListReader is a Reader for the DeviceGroupsList structure.
type DeviceGroupsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeviceGroupsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeviceGroupsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeviceGroupsListOK creates a DeviceGroupsListOK with default headers values
func NewDeviceGroupsListOK() *DeviceGroupsListOK {
	return &DeviceGroupsListOK{}
}

/*DeviceGroupsListOK handles this case with default header values.

Success
*/
type DeviceGroupsListOK struct {
	Payload *models.DeviceGroupCollection
}

func (o *DeviceGroupsListOK) Error() string {
	return fmt.Sprintf("[GET /deviceGroups][%d] deviceGroupsListOK  %+v", 200, o.Payload)
}

func (o *DeviceGroupsListOK) GetPayload() *models.DeviceGroupCollection {
	return o.Payload
}

func (o *DeviceGroupsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceGroupCollection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
