// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDevicesGetModuleComponentTelemetryValueParams creates a new DevicesGetModuleComponentTelemetryValueParams object
// with the default values initialized.
func NewDevicesGetModuleComponentTelemetryValueParams() *DevicesGetModuleComponentTelemetryValueParams {
	var ()
	return &DevicesGetModuleComponentTelemetryValueParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesGetModuleComponentTelemetryValueParamsWithTimeout creates a new DevicesGetModuleComponentTelemetryValueParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesGetModuleComponentTelemetryValueParamsWithTimeout(timeout time.Duration) *DevicesGetModuleComponentTelemetryValueParams {
	var ()
	return &DevicesGetModuleComponentTelemetryValueParams{

		timeout: timeout,
	}
}

// NewDevicesGetModuleComponentTelemetryValueParamsWithContext creates a new DevicesGetModuleComponentTelemetryValueParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesGetModuleComponentTelemetryValueParamsWithContext(ctx context.Context) *DevicesGetModuleComponentTelemetryValueParams {
	var ()
	return &DevicesGetModuleComponentTelemetryValueParams{

		Context: ctx,
	}
}

// NewDevicesGetModuleComponentTelemetryValueParamsWithHTTPClient creates a new DevicesGetModuleComponentTelemetryValueParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesGetModuleComponentTelemetryValueParamsWithHTTPClient(client *http.Client) *DevicesGetModuleComponentTelemetryValueParams {
	var ()
	return &DevicesGetModuleComponentTelemetryValueParams{
		HTTPClient: client,
	}
}

/*DevicesGetModuleComponentTelemetryValueParams contains all the parameters to send to the API endpoint
for the devices get module component telemetry value operation typically these are written to a http.Request
*/
type DevicesGetModuleComponentTelemetryValueParams struct {

	/*ComponentName
	  Name of the device component.

	*/
	ComponentName string
	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string
	/*ModuleName
	  Name of the device module.

	*/
	ModuleName string
	/*TelemetryName
	  Name of this device telemetry.

	*/
	TelemetryName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices get module component telemetry value params
func (o *DevicesGetModuleComponentTelemetryValueParams) WithTimeout(timeout time.Duration) *DevicesGetModuleComponentTelemetryValueParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices get module component telemetry value params
func (o *DevicesGetModuleComponentTelemetryValueParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices get module component telemetry value params
func (o *DevicesGetModuleComponentTelemetryValueParams) WithContext(ctx context.Context) *DevicesGetModuleComponentTelemetryValueParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices get module component telemetry value params
func (o *DevicesGetModuleComponentTelemetryValueParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices get module component telemetry value params
func (o *DevicesGetModuleComponentTelemetryValueParams) WithHTTPClient(client *http.Client) *DevicesGetModuleComponentTelemetryValueParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices get module component telemetry value params
func (o *DevicesGetModuleComponentTelemetryValueParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithComponentName adds the componentName to the devices get module component telemetry value params
func (o *DevicesGetModuleComponentTelemetryValueParams) WithComponentName(componentName string) *DevicesGetModuleComponentTelemetryValueParams {
	o.SetComponentName(componentName)
	return o
}

// SetComponentName adds the componentName to the devices get module component telemetry value params
func (o *DevicesGetModuleComponentTelemetryValueParams) SetComponentName(componentName string) {
	o.ComponentName = componentName
}

// WithDeviceID adds the deviceID to the devices get module component telemetry value params
func (o *DevicesGetModuleComponentTelemetryValueParams) WithDeviceID(deviceID string) *DevicesGetModuleComponentTelemetryValueParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices get module component telemetry value params
func (o *DevicesGetModuleComponentTelemetryValueParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WithModuleName adds the moduleName to the devices get module component telemetry value params
func (o *DevicesGetModuleComponentTelemetryValueParams) WithModuleName(moduleName string) *DevicesGetModuleComponentTelemetryValueParams {
	o.SetModuleName(moduleName)
	return o
}

// SetModuleName adds the moduleName to the devices get module component telemetry value params
func (o *DevicesGetModuleComponentTelemetryValueParams) SetModuleName(moduleName string) {
	o.ModuleName = moduleName
}

// WithTelemetryName adds the telemetryName to the devices get module component telemetry value params
func (o *DevicesGetModuleComponentTelemetryValueParams) WithTelemetryName(telemetryName string) *DevicesGetModuleComponentTelemetryValueParams {
	o.SetTelemetryName(telemetryName)
	return o
}

// SetTelemetryName adds the telemetryName to the devices get module component telemetry value params
func (o *DevicesGetModuleComponentTelemetryValueParams) SetTelemetryName(telemetryName string) {
	o.TelemetryName = telemetryName
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesGetModuleComponentTelemetryValueParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param component_name
	if err := r.SetPathParam("component_name", o.ComponentName); err != nil {
		return err
	}

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	// path param module_name
	if err := r.SetPathParam("module_name", o.ModuleName); err != nil {
		return err
	}

	// path param telemetry_name
	if err := r.SetPathParam("telemetry_name", o.TelemetryName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
