// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// NewDevicesUpdateComponentPropertiesParams creates a new DevicesUpdateComponentPropertiesParams object
// with the default values initialized.
func NewDevicesUpdateComponentPropertiesParams() *DevicesUpdateComponentPropertiesParams {
	var ()
	return &DevicesUpdateComponentPropertiesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesUpdateComponentPropertiesParamsWithTimeout creates a new DevicesUpdateComponentPropertiesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesUpdateComponentPropertiesParamsWithTimeout(timeout time.Duration) *DevicesUpdateComponentPropertiesParams {
	var ()
	return &DevicesUpdateComponentPropertiesParams{

		timeout: timeout,
	}
}

// NewDevicesUpdateComponentPropertiesParamsWithContext creates a new DevicesUpdateComponentPropertiesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesUpdateComponentPropertiesParamsWithContext(ctx context.Context) *DevicesUpdateComponentPropertiesParams {
	var ()
	return &DevicesUpdateComponentPropertiesParams{

		Context: ctx,
	}
}

// NewDevicesUpdateComponentPropertiesParamsWithHTTPClient creates a new DevicesUpdateComponentPropertiesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesUpdateComponentPropertiesParamsWithHTTPClient(client *http.Client) *DevicesUpdateComponentPropertiesParams {
	var ()
	return &DevicesUpdateComponentPropertiesParams{
		HTTPClient: client,
	}
}

/*DevicesUpdateComponentPropertiesParams contains all the parameters to send to the API endpoint
for the devices update component properties operation typically these are written to a http.Request
*/
type DevicesUpdateComponentPropertiesParams struct {

	/*Body
	  Device properties.

	*/
	Body models.DeviceProperties
	/*ComponentName
	  Name of the device component.

	*/
	ComponentName string
	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices update component properties params
func (o *DevicesUpdateComponentPropertiesParams) WithTimeout(timeout time.Duration) *DevicesUpdateComponentPropertiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices update component properties params
func (o *DevicesUpdateComponentPropertiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices update component properties params
func (o *DevicesUpdateComponentPropertiesParams) WithContext(ctx context.Context) *DevicesUpdateComponentPropertiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices update component properties params
func (o *DevicesUpdateComponentPropertiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices update component properties params
func (o *DevicesUpdateComponentPropertiesParams) WithHTTPClient(client *http.Client) *DevicesUpdateComponentPropertiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices update component properties params
func (o *DevicesUpdateComponentPropertiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the devices update component properties params
func (o *DevicesUpdateComponentPropertiesParams) WithBody(body models.DeviceProperties) *DevicesUpdateComponentPropertiesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the devices update component properties params
func (o *DevicesUpdateComponentPropertiesParams) SetBody(body models.DeviceProperties) {
	o.Body = body
}

// WithComponentName adds the componentName to the devices update component properties params
func (o *DevicesUpdateComponentPropertiesParams) WithComponentName(componentName string) *DevicesUpdateComponentPropertiesParams {
	o.SetComponentName(componentName)
	return o
}

// SetComponentName adds the componentName to the devices update component properties params
func (o *DevicesUpdateComponentPropertiesParams) SetComponentName(componentName string) {
	o.ComponentName = componentName
}

// WithDeviceID adds the deviceID to the devices update component properties params
func (o *DevicesUpdateComponentPropertiesParams) WithDeviceID(deviceID string) *DevicesUpdateComponentPropertiesParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices update component properties params
func (o *DevicesUpdateComponentPropertiesParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesUpdateComponentPropertiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param component_name
	if err := r.SetPathParam("component_name", o.ComponentName); err != nil {
		return err
	}

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
