// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeviceTemplatesGetMergedParams creates a new DeviceTemplatesGetMergedParams object
// with the default values initialized.
func NewDeviceTemplatesGetMergedParams() *DeviceTemplatesGetMergedParams {
	var ()
	return &DeviceTemplatesGetMergedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeviceTemplatesGetMergedParamsWithTimeout creates a new DeviceTemplatesGetMergedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeviceTemplatesGetMergedParamsWithTimeout(timeout time.Duration) *DeviceTemplatesGetMergedParams {
	var ()
	return &DeviceTemplatesGetMergedParams{

		timeout: timeout,
	}
}

// NewDeviceTemplatesGetMergedParamsWithContext creates a new DeviceTemplatesGetMergedParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeviceTemplatesGetMergedParamsWithContext(ctx context.Context) *DeviceTemplatesGetMergedParams {
	var ()
	return &DeviceTemplatesGetMergedParams{

		Context: ctx,
	}
}

// NewDeviceTemplatesGetMergedParamsWithHTTPClient creates a new DeviceTemplatesGetMergedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeviceTemplatesGetMergedParamsWithHTTPClient(client *http.Client) *DeviceTemplatesGetMergedParams {
	var ()
	return &DeviceTemplatesGetMergedParams{
		HTTPClient: client,
	}
}

/*DeviceTemplatesGetMergedParams contains all the parameters to send to the API endpoint
for the device templates get merged operation typically these are written to a http.Request
*/
type DeviceTemplatesGetMergedParams struct {

	/*DeviceTemplateID
	  Unique ID of the device template.

	*/
	DeviceTemplateID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the device templates get merged params
func (o *DeviceTemplatesGetMergedParams) WithTimeout(timeout time.Duration) *DeviceTemplatesGetMergedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the device templates get merged params
func (o *DeviceTemplatesGetMergedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the device templates get merged params
func (o *DeviceTemplatesGetMergedParams) WithContext(ctx context.Context) *DeviceTemplatesGetMergedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the device templates get merged params
func (o *DeviceTemplatesGetMergedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the device templates get merged params
func (o *DeviceTemplatesGetMergedParams) WithHTTPClient(client *http.Client) *DeviceTemplatesGetMergedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the device templates get merged params
func (o *DeviceTemplatesGetMergedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceTemplateID adds the deviceTemplateID to the device templates get merged params
func (o *DeviceTemplatesGetMergedParams) WithDeviceTemplateID(deviceTemplateID string) *DeviceTemplatesGetMergedParams {
	o.SetDeviceTemplateID(deviceTemplateID)
	return o
}

// SetDeviceTemplateID adds the deviceTemplateId to the device templates get merged params
func (o *DeviceTemplatesGetMergedParams) SetDeviceTemplateID(deviceTemplateID string) {
	o.DeviceTemplateID = deviceTemplateID
}

// WriteToRequest writes these params to a swagger request
func (o *DeviceTemplatesGetMergedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param device_template_id
	if err := r.SetPathParam("device_template_id", o.DeviceTemplateID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
