// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDevicesGetPropertiesParams creates a new DevicesGetPropertiesParams object
// with the default values initialized.
func NewDevicesGetPropertiesParams() *DevicesGetPropertiesParams {
	var ()
	return &DevicesGetPropertiesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesGetPropertiesParamsWithTimeout creates a new DevicesGetPropertiesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesGetPropertiesParamsWithTimeout(timeout time.Duration) *DevicesGetPropertiesParams {
	var ()
	return &DevicesGetPropertiesParams{

		timeout: timeout,
	}
}

// NewDevicesGetPropertiesParamsWithContext creates a new DevicesGetPropertiesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesGetPropertiesParamsWithContext(ctx context.Context) *DevicesGetPropertiesParams {
	var ()
	return &DevicesGetPropertiesParams{

		Context: ctx,
	}
}

// NewDevicesGetPropertiesParamsWithHTTPClient creates a new DevicesGetPropertiesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesGetPropertiesParamsWithHTTPClient(client *http.Client) *DevicesGetPropertiesParams {
	var ()
	return &DevicesGetPropertiesParams{
		HTTPClient: client,
	}
}

/*DevicesGetPropertiesParams contains all the parameters to send to the API endpoint
for the devices get properties operation typically these are written to a http.Request
*/
type DevicesGetPropertiesParams struct {

	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices get properties params
func (o *DevicesGetPropertiesParams) WithTimeout(timeout time.Duration) *DevicesGetPropertiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices get properties params
func (o *DevicesGetPropertiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices get properties params
func (o *DevicesGetPropertiesParams) WithContext(ctx context.Context) *DevicesGetPropertiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices get properties params
func (o *DevicesGetPropertiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices get properties params
func (o *DevicesGetPropertiesParams) WithHTTPClient(client *http.Client) *DevicesGetPropertiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices get properties params
func (o *DevicesGetPropertiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the devices get properties params
func (o *DevicesGetPropertiesParams) WithDeviceID(deviceID string) *DevicesGetPropertiesParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices get properties params
func (o *DevicesGetPropertiesParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesGetPropertiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
