// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// DevicesListModuleComponentsReader is a Reader for the DevicesListModuleComponents structure.
type DevicesListModuleComponentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DevicesListModuleComponentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDevicesListModuleComponentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDevicesListModuleComponentsOK creates a DevicesListModuleComponentsOK with default headers values
func NewDevicesListModuleComponentsOK() *DevicesListModuleComponentsOK {
	return &DevicesListModuleComponentsOK{}
}

/*DevicesListModuleComponentsOK handles this case with default header values.

Success
*/
type DevicesListModuleComponentsOK struct {
	Payload *models.Collection
}

func (o *DevicesListModuleComponentsOK) Error() string {
	return fmt.Sprintf("[GET /devices/{device_id}/modules/{module_name}/components][%d] devicesListModuleComponentsOK  %+v", 200, o.Payload)
}

func (o *DevicesListModuleComponentsOK) GetPayload() *models.Collection {
	return o.Payload
}

func (o *DevicesListModuleComponentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Collection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
