// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// DevicesGetModuleTelemetryValueReader is a Reader for the DevicesGetModuleTelemetryValue structure.
type DevicesGetModuleTelemetryValueReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DevicesGetModuleTelemetryValueReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDevicesGetModuleTelemetryValueOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDevicesGetModuleTelemetryValueOK creates a DevicesGetModuleTelemetryValueOK with default headers values
func NewDevicesGetModuleTelemetryValueOK() *DevicesGetModuleTelemetryValueOK {
	return &DevicesGetModuleTelemetryValueOK{}
}

/*DevicesGetModuleTelemetryValueOK handles this case with default header values.

Success
*/
type DevicesGetModuleTelemetryValueOK struct {
	Payload *models.DeviceTelemetry
}

func (o *DevicesGetModuleTelemetryValueOK) Error() string {
	return fmt.Sprintf("[GET /devices/{device_id}/modules/{module_name}/telemetry/{telemetry_name}][%d] devicesGetModuleTelemetryValueOK  %+v", 200, o.Payload)
}

func (o *DevicesGetModuleTelemetryValueOK) GetPayload() *models.DeviceTelemetry {
	return o.Payload
}

func (o *DevicesGetModuleTelemetryValueOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceTelemetry)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
