// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// NewDevicesUpdateCloudPropertiesParams creates a new DevicesUpdateCloudPropertiesParams object
// with the default values initialized.
func NewDevicesUpdateCloudPropertiesParams() *DevicesUpdateCloudPropertiesParams {
	var ()
	return &DevicesUpdateCloudPropertiesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesUpdateCloudPropertiesParamsWithTimeout creates a new DevicesUpdateCloudPropertiesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesUpdateCloudPropertiesParamsWithTimeout(timeout time.Duration) *DevicesUpdateCloudPropertiesParams {
	var ()
	return &DevicesUpdateCloudPropertiesParams{

		timeout: timeout,
	}
}

// NewDevicesUpdateCloudPropertiesParamsWithContext creates a new DevicesUpdateCloudPropertiesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesUpdateCloudPropertiesParamsWithContext(ctx context.Context) *DevicesUpdateCloudPropertiesParams {
	var ()
	return &DevicesUpdateCloudPropertiesParams{

		Context: ctx,
	}
}

// NewDevicesUpdateCloudPropertiesParamsWithHTTPClient creates a new DevicesUpdateCloudPropertiesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesUpdateCloudPropertiesParamsWithHTTPClient(client *http.Client) *DevicesUpdateCloudPropertiesParams {
	var ()
	return &DevicesUpdateCloudPropertiesParams{
		HTTPClient: client,
	}
}

/*DevicesUpdateCloudPropertiesParams contains all the parameters to send to the API endpoint
for the devices update cloud properties operation typically these are written to a http.Request
*/
type DevicesUpdateCloudPropertiesParams struct {

	/*Body
	  Device properties.

	*/
	Body models.DeviceCloudProperties
	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices update cloud properties params
func (o *DevicesUpdateCloudPropertiesParams) WithTimeout(timeout time.Duration) *DevicesUpdateCloudPropertiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices update cloud properties params
func (o *DevicesUpdateCloudPropertiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices update cloud properties params
func (o *DevicesUpdateCloudPropertiesParams) WithContext(ctx context.Context) *DevicesUpdateCloudPropertiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices update cloud properties params
func (o *DevicesUpdateCloudPropertiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices update cloud properties params
func (o *DevicesUpdateCloudPropertiesParams) WithHTTPClient(client *http.Client) *DevicesUpdateCloudPropertiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices update cloud properties params
func (o *DevicesUpdateCloudPropertiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the devices update cloud properties params
func (o *DevicesUpdateCloudPropertiesParams) WithBody(body models.DeviceCloudProperties) *DevicesUpdateCloudPropertiesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the devices update cloud properties params
func (o *DevicesUpdateCloudPropertiesParams) SetBody(body models.DeviceCloudProperties) {
	o.Body = body
}

// WithDeviceID adds the deviceID to the devices update cloud properties params
func (o *DevicesUpdateCloudPropertiesParams) WithDeviceID(deviceID string) *DevicesUpdateCloudPropertiesParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices update cloud properties params
func (o *DevicesUpdateCloudPropertiesParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesUpdateCloudPropertiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
