// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeviceTemplatesListDevicesParams creates a new DeviceTemplatesListDevicesParams object
// with the default values initialized.
func NewDeviceTemplatesListDevicesParams() *DeviceTemplatesListDevicesParams {
	var ()
	return &DeviceTemplatesListDevicesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeviceTemplatesListDevicesParamsWithTimeout creates a new DeviceTemplatesListDevicesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeviceTemplatesListDevicesParamsWithTimeout(timeout time.Duration) *DeviceTemplatesListDevicesParams {
	var ()
	return &DeviceTemplatesListDevicesParams{

		timeout: timeout,
	}
}

// NewDeviceTemplatesListDevicesParamsWithContext creates a new DeviceTemplatesListDevicesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeviceTemplatesListDevicesParamsWithContext(ctx context.Context) *DeviceTemplatesListDevicesParams {
	var ()
	return &DeviceTemplatesListDevicesParams{

		Context: ctx,
	}
}

// NewDeviceTemplatesListDevicesParamsWithHTTPClient creates a new DeviceTemplatesListDevicesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeviceTemplatesListDevicesParamsWithHTTPClient(client *http.Client) *DeviceTemplatesListDevicesParams {
	var ()
	return &DeviceTemplatesListDevicesParams{
		HTTPClient: client,
	}
}

/*DeviceTemplatesListDevicesParams contains all the parameters to send to the API endpoint
for the device templates list devices operation typically these are written to a http.Request
*/
type DeviceTemplatesListDevicesParams struct {

	/*DeviceTemplateID
	  Unique ID of the device template.

	*/
	DeviceTemplateID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the device templates list devices params
func (o *DeviceTemplatesListDevicesParams) WithTimeout(timeout time.Duration) *DeviceTemplatesListDevicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the device templates list devices params
func (o *DeviceTemplatesListDevicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the device templates list devices params
func (o *DeviceTemplatesListDevicesParams) WithContext(ctx context.Context) *DeviceTemplatesListDevicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the device templates list devices params
func (o *DeviceTemplatesListDevicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the device templates list devices params
func (o *DeviceTemplatesListDevicesParams) WithHTTPClient(client *http.Client) *DeviceTemplatesListDevicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the device templates list devices params
func (o *DeviceTemplatesListDevicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceTemplateID adds the deviceTemplateID to the device templates list devices params
func (o *DeviceTemplatesListDevicesParams) WithDeviceTemplateID(deviceTemplateID string) *DeviceTemplatesListDevicesParams {
	o.SetDeviceTemplateID(deviceTemplateID)
	return o
}

// SetDeviceTemplateID adds the deviceTemplateId to the device templates list devices params
func (o *DeviceTemplatesListDevicesParams) SetDeviceTemplateID(deviceTemplateID string) {
	o.DeviceTemplateID = deviceTemplateID
}

// WriteToRequest writes these params to a swagger request
func (o *DeviceTemplatesListDevicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param device_template_id
	if err := r.SetPathParam("device_template_id", o.DeviceTemplateID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
