// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DevicesRemoveReader is a Reader for the DevicesRemove structure.
type DevicesRemoveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DevicesRemoveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDevicesRemoveNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDevicesRemoveNoContent creates a DevicesRemoveNoContent with default headers values
func NewDevicesRemoveNoContent() *DevicesRemoveNoContent {
	return &DevicesRemoveNoContent{}
}

/*DevicesRemoveNoContent handles this case with default header values.

Success
*/
type DevicesRemoveNoContent struct {
}

func (o *DevicesRemoveNoContent) Error() string {
	return fmt.Sprintf("[DELETE /devices/{device_id}][%d] devicesRemoveNoContent ", 204)
}

func (o *DevicesRemoveNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
