// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeviceTemplatesListParams creates a new DeviceTemplatesListParams object
// with the default values initialized.
func NewDeviceTemplatesListParams() *DeviceTemplatesListParams {

	return &DeviceTemplatesListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeviceTemplatesListParamsWithTimeout creates a new DeviceTemplatesListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeviceTemplatesListParamsWithTimeout(timeout time.Duration) *DeviceTemplatesListParams {

	return &DeviceTemplatesListParams{

		timeout: timeout,
	}
}

// NewDeviceTemplatesListParamsWithContext creates a new DeviceTemplatesListParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeviceTemplatesListParamsWithContext(ctx context.Context) *DeviceTemplatesListParams {

	return &DeviceTemplatesListParams{

		Context: ctx,
	}
}

// NewDeviceTemplatesListParamsWithHTTPClient creates a new DeviceTemplatesListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeviceTemplatesListParamsWithHTTPClient(client *http.Client) *DeviceTemplatesListParams {

	return &DeviceTemplatesListParams{
		HTTPClient: client,
	}
}

/*DeviceTemplatesListParams contains all the parameters to send to the API endpoint
for the device templates list operation typically these are written to a http.Request
*/
type DeviceTemplatesListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the device templates list params
func (o *DeviceTemplatesListParams) WithTimeout(timeout time.Duration) *DeviceTemplatesListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the device templates list params
func (o *DeviceTemplatesListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the device templates list params
func (o *DeviceTemplatesListParams) WithContext(ctx context.Context) *DeviceTemplatesListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the device templates list params
func (o *DeviceTemplatesListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the device templates list params
func (o *DeviceTemplatesListParams) WithHTTPClient(client *http.Client) *DeviceTemplatesListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the device templates list params
func (o *DeviceTemplatesListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeviceTemplatesListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
