// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDevicesGetModuleParams creates a new DevicesGetModuleParams object
// with the default values initialized.
func NewDevicesGetModuleParams() *DevicesGetModuleParams {
	var ()
	return &DevicesGetModuleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesGetModuleParamsWithTimeout creates a new DevicesGetModuleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesGetModuleParamsWithTimeout(timeout time.Duration) *DevicesGetModuleParams {
	var ()
	return &DevicesGetModuleParams{

		timeout: timeout,
	}
}

// NewDevicesGetModuleParamsWithContext creates a new DevicesGetModuleParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesGetModuleParamsWithContext(ctx context.Context) *DevicesGetModuleParams {
	var ()
	return &DevicesGetModuleParams{

		Context: ctx,
	}
}

// NewDevicesGetModuleParamsWithHTTPClient creates a new DevicesGetModuleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesGetModuleParamsWithHTTPClient(client *http.Client) *DevicesGetModuleParams {
	var ()
	return &DevicesGetModuleParams{
		HTTPClient: client,
	}
}

/*DevicesGetModuleParams contains all the parameters to send to the API endpoint
for the devices get module operation typically these are written to a http.Request
*/
type DevicesGetModuleParams struct {

	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string
	/*ModuleName
	  Name of the device module.

	*/
	ModuleName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices get module params
func (o *DevicesGetModuleParams) WithTimeout(timeout time.Duration) *DevicesGetModuleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices get module params
func (o *DevicesGetModuleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices get module params
func (o *DevicesGetModuleParams) WithContext(ctx context.Context) *DevicesGetModuleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices get module params
func (o *DevicesGetModuleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices get module params
func (o *DevicesGetModuleParams) WithHTTPClient(client *http.Client) *DevicesGetModuleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices get module params
func (o *DevicesGetModuleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the devices get module params
func (o *DevicesGetModuleParams) WithDeviceID(deviceID string) *DevicesGetModuleParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices get module params
func (o *DevicesGetModuleParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WithModuleName adds the moduleName to the devices get module params
func (o *DevicesGetModuleParams) WithModuleName(moduleName string) *DevicesGetModuleParams {
	o.SetModuleName(moduleName)
	return o
}

// SetModuleName adds the moduleName to the devices get module params
func (o *DevicesGetModuleParams) SetModuleName(moduleName string) {
	o.ModuleName = moduleName
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesGetModuleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	// path param module_name
	if err := r.SetPathParam("module_name", o.ModuleName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
