// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDevicesListModuleComponentsParams creates a new DevicesListModuleComponentsParams object
// with the default values initialized.
func NewDevicesListModuleComponentsParams() *DevicesListModuleComponentsParams {
	var ()
	return &DevicesListModuleComponentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesListModuleComponentsParamsWithTimeout creates a new DevicesListModuleComponentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesListModuleComponentsParamsWithTimeout(timeout time.Duration) *DevicesListModuleComponentsParams {
	var ()
	return &DevicesListModuleComponentsParams{

		timeout: timeout,
	}
}

// NewDevicesListModuleComponentsParamsWithContext creates a new DevicesListModuleComponentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesListModuleComponentsParamsWithContext(ctx context.Context) *DevicesListModuleComponentsParams {
	var ()
	return &DevicesListModuleComponentsParams{

		Context: ctx,
	}
}

// NewDevicesListModuleComponentsParamsWithHTTPClient creates a new DevicesListModuleComponentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesListModuleComponentsParamsWithHTTPClient(client *http.Client) *DevicesListModuleComponentsParams {
	var ()
	return &DevicesListModuleComponentsParams{
		HTTPClient: client,
	}
}

/*DevicesListModuleComponentsParams contains all the parameters to send to the API endpoint
for the devices list module components operation typically these are written to a http.Request
*/
type DevicesListModuleComponentsParams struct {

	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string
	/*ModuleName
	  Name of the device module.

	*/
	ModuleName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices list module components params
func (o *DevicesListModuleComponentsParams) WithTimeout(timeout time.Duration) *DevicesListModuleComponentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices list module components params
func (o *DevicesListModuleComponentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices list module components params
func (o *DevicesListModuleComponentsParams) WithContext(ctx context.Context) *DevicesListModuleComponentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices list module components params
func (o *DevicesListModuleComponentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices list module components params
func (o *DevicesListModuleComponentsParams) WithHTTPClient(client *http.Client) *DevicesListModuleComponentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices list module components params
func (o *DevicesListModuleComponentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the devices list module components params
func (o *DevicesListModuleComponentsParams) WithDeviceID(deviceID string) *DevicesListModuleComponentsParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices list module components params
func (o *DevicesListModuleComponentsParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WithModuleName adds the moduleName to the devices list module components params
func (o *DevicesListModuleComponentsParams) WithModuleName(moduleName string) *DevicesListModuleComponentsParams {
	o.SetModuleName(moduleName)
	return o
}

// SetModuleName adds the moduleName to the devices list module components params
func (o *DevicesListModuleComponentsParams) SetModuleName(moduleName string) {
	o.ModuleName = moduleName
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesListModuleComponentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	// path param module_name
	if err := r.SetPathParam("module_name", o.ModuleName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
