// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// NewDevicesExecuteModuleComponentCommandParams creates a new DevicesExecuteModuleComponentCommandParams object
// with the default values initialized.
func NewDevicesExecuteModuleComponentCommandParams() *DevicesExecuteModuleComponentCommandParams {
	var ()
	return &DevicesExecuteModuleComponentCommandParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesExecuteModuleComponentCommandParamsWithTimeout creates a new DevicesExecuteModuleComponentCommandParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesExecuteModuleComponentCommandParamsWithTimeout(timeout time.Duration) *DevicesExecuteModuleComponentCommandParams {
	var ()
	return &DevicesExecuteModuleComponentCommandParams{

		timeout: timeout,
	}
}

// NewDevicesExecuteModuleComponentCommandParamsWithContext creates a new DevicesExecuteModuleComponentCommandParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesExecuteModuleComponentCommandParamsWithContext(ctx context.Context) *DevicesExecuteModuleComponentCommandParams {
	var ()
	return &DevicesExecuteModuleComponentCommandParams{

		Context: ctx,
	}
}

// NewDevicesExecuteModuleComponentCommandParamsWithHTTPClient creates a new DevicesExecuteModuleComponentCommandParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesExecuteModuleComponentCommandParamsWithHTTPClient(client *http.Client) *DevicesExecuteModuleComponentCommandParams {
	var ()
	return &DevicesExecuteModuleComponentCommandParams{
		HTTPClient: client,
	}
}

/*DevicesExecuteModuleComponentCommandParams contains all the parameters to send to the API endpoint
for the devices execute module component command operation typically these are written to a http.Request
*/
type DevicesExecuteModuleComponentCommandParams struct {

	/*Body
	  Device command body.

	*/
	Body *models.DeviceCommand
	/*CommandName
	  Name of this device command.

	*/
	CommandName string
	/*ComponentName
	  Name of the device component.

	*/
	ComponentName string
	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string
	/*ModuleName
	  Name of the device module.

	*/
	ModuleName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices execute module component command params
func (o *DevicesExecuteModuleComponentCommandParams) WithTimeout(timeout time.Duration) *DevicesExecuteModuleComponentCommandParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices execute module component command params
func (o *DevicesExecuteModuleComponentCommandParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices execute module component command params
func (o *DevicesExecuteModuleComponentCommandParams) WithContext(ctx context.Context) *DevicesExecuteModuleComponentCommandParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices execute module component command params
func (o *DevicesExecuteModuleComponentCommandParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices execute module component command params
func (o *DevicesExecuteModuleComponentCommandParams) WithHTTPClient(client *http.Client) *DevicesExecuteModuleComponentCommandParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices execute module component command params
func (o *DevicesExecuteModuleComponentCommandParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the devices execute module component command params
func (o *DevicesExecuteModuleComponentCommandParams) WithBody(body *models.DeviceCommand) *DevicesExecuteModuleComponentCommandParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the devices execute module component command params
func (o *DevicesExecuteModuleComponentCommandParams) SetBody(body *models.DeviceCommand) {
	o.Body = body
}

// WithCommandName adds the commandName to the devices execute module component command params
func (o *DevicesExecuteModuleComponentCommandParams) WithCommandName(commandName string) *DevicesExecuteModuleComponentCommandParams {
	o.SetCommandName(commandName)
	return o
}

// SetCommandName adds the commandName to the devices execute module component command params
func (o *DevicesExecuteModuleComponentCommandParams) SetCommandName(commandName string) {
	o.CommandName = commandName
}

// WithComponentName adds the componentName to the devices execute module component command params
func (o *DevicesExecuteModuleComponentCommandParams) WithComponentName(componentName string) *DevicesExecuteModuleComponentCommandParams {
	o.SetComponentName(componentName)
	return o
}

// SetComponentName adds the componentName to the devices execute module component command params
func (o *DevicesExecuteModuleComponentCommandParams) SetComponentName(componentName string) {
	o.ComponentName = componentName
}

// WithDeviceID adds the deviceID to the devices execute module component command params
func (o *DevicesExecuteModuleComponentCommandParams) WithDeviceID(deviceID string) *DevicesExecuteModuleComponentCommandParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices execute module component command params
func (o *DevicesExecuteModuleComponentCommandParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WithModuleName adds the moduleName to the devices execute module component command params
func (o *DevicesExecuteModuleComponentCommandParams) WithModuleName(moduleName string) *DevicesExecuteModuleComponentCommandParams {
	o.SetModuleName(moduleName)
	return o
}

// SetModuleName adds the moduleName to the devices execute module component command params
func (o *DevicesExecuteModuleComponentCommandParams) SetModuleName(moduleName string) {
	o.ModuleName = moduleName
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesExecuteModuleComponentCommandParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param command_name
	if err := r.SetPathParam("command_name", o.CommandName); err != nil {
		return err
	}

	// path param component_name
	if err := r.SetPathParam("component_name", o.ComponentName); err != nil {
		return err
	}

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	// path param module_name
	if err := r.SetPathParam("module_name", o.ModuleName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
