// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeviceTemplatesRemoveParams creates a new DeviceTemplatesRemoveParams object
// with the default values initialized.
func NewDeviceTemplatesRemoveParams() *DeviceTemplatesRemoveParams {
	var ()
	return &DeviceTemplatesRemoveParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeviceTemplatesRemoveParamsWithTimeout creates a new DeviceTemplatesRemoveParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeviceTemplatesRemoveParamsWithTimeout(timeout time.Duration) *DeviceTemplatesRemoveParams {
	var ()
	return &DeviceTemplatesRemoveParams{

		timeout: timeout,
	}
}

// NewDeviceTemplatesRemoveParamsWithContext creates a new DeviceTemplatesRemoveParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeviceTemplatesRemoveParamsWithContext(ctx context.Context) *DeviceTemplatesRemoveParams {
	var ()
	return &DeviceTemplatesRemoveParams{

		Context: ctx,
	}
}

// NewDeviceTemplatesRemoveParamsWithHTTPClient creates a new DeviceTemplatesRemoveParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeviceTemplatesRemoveParamsWithHTTPClient(client *http.Client) *DeviceTemplatesRemoveParams {
	var ()
	return &DeviceTemplatesRemoveParams{
		HTTPClient: client,
	}
}

/*DeviceTemplatesRemoveParams contains all the parameters to send to the API endpoint
for the device templates remove operation typically these are written to a http.Request
*/
type DeviceTemplatesRemoveParams struct {

	/*DeviceTemplateID
	  Unique ID of the device template.

	*/
	DeviceTemplateID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the device templates remove params
func (o *DeviceTemplatesRemoveParams) WithTimeout(timeout time.Duration) *DeviceTemplatesRemoveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the device templates remove params
func (o *DeviceTemplatesRemoveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the device templates remove params
func (o *DeviceTemplatesRemoveParams) WithContext(ctx context.Context) *DeviceTemplatesRemoveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the device templates remove params
func (o *DeviceTemplatesRemoveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the device templates remove params
func (o *DeviceTemplatesRemoveParams) WithHTTPClient(client *http.Client) *DeviceTemplatesRemoveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the device templates remove params
func (o *DeviceTemplatesRemoveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceTemplateID adds the deviceTemplateID to the device templates remove params
func (o *DeviceTemplatesRemoveParams) WithDeviceTemplateID(deviceTemplateID string) *DeviceTemplatesRemoveParams {
	o.SetDeviceTemplateID(deviceTemplateID)
	return o
}

// SetDeviceTemplateID adds the deviceTemplateId to the device templates remove params
func (o *DeviceTemplatesRemoveParams) SetDeviceTemplateID(deviceTemplateID string) {
	o.DeviceTemplateID = deviceTemplateID
}

// WriteToRequest writes these params to a swagger request
func (o *DeviceTemplatesRemoveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param device_template_id
	if err := r.SetPathParam("device_template_id", o.DeviceTemplateID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
