// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDevicesListComponentsParams creates a new DevicesListComponentsParams object
// with the default values initialized.
func NewDevicesListComponentsParams() *DevicesListComponentsParams {
	var ()
	return &DevicesListComponentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDevicesListComponentsParamsWithTimeout creates a new DevicesListComponentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDevicesListComponentsParamsWithTimeout(timeout time.Duration) *DevicesListComponentsParams {
	var ()
	return &DevicesListComponentsParams{

		timeout: timeout,
	}
}

// NewDevicesListComponentsParamsWithContext creates a new DevicesListComponentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDevicesListComponentsParamsWithContext(ctx context.Context) *DevicesListComponentsParams {
	var ()
	return &DevicesListComponentsParams{

		Context: ctx,
	}
}

// NewDevicesListComponentsParamsWithHTTPClient creates a new DevicesListComponentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDevicesListComponentsParamsWithHTTPClient(client *http.Client) *DevicesListComponentsParams {
	var ()
	return &DevicesListComponentsParams{
		HTTPClient: client,
	}
}

/*DevicesListComponentsParams contains all the parameters to send to the API endpoint
for the devices list components operation typically these are written to a http.Request
*/
type DevicesListComponentsParams struct {

	/*DeviceID
	  Unique ID of the device.

	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the devices list components params
func (o *DevicesListComponentsParams) WithTimeout(timeout time.Duration) *DevicesListComponentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the devices list components params
func (o *DevicesListComponentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the devices list components params
func (o *DevicesListComponentsParams) WithContext(ctx context.Context) *DevicesListComponentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the devices list components params
func (o *DevicesListComponentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the devices list components params
func (o *DevicesListComponentsParams) WithHTTPClient(client *http.Client) *DevicesListComponentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the devices list components params
func (o *DevicesListComponentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the devices list components params
func (o *DevicesListComponentsParams) WithDeviceID(deviceID string) *DevicesListComponentsParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the devices list components params
func (o *DevicesListComponentsParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *DevicesListComponentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param device_id
	if err := r.SetPathParam("device_id", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
