// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// JobsGetDevicesReader is a Reader for the JobsGetDevices structure.
type JobsGetDevicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JobsGetDevicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewJobsGetDevicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewJobsGetDevicesOK creates a JobsGetDevicesOK with default headers values
func NewJobsGetDevicesOK() *JobsGetDevicesOK {
	return &JobsGetDevicesOK{}
}

/*JobsGetDevicesOK handles this case with default header values.

Success
*/
type JobsGetDevicesOK struct {
	Payload *models.JobDeviceStatusCollection
}

func (o *JobsGetDevicesOK) Error() string {
	return fmt.Sprintf("[GET /jobs/{job_id}/devices][%d] jobsGetDevicesOK  %+v", 200, o.Payload)
}

func (o *JobsGetDevicesOK) GetPayload() *models.JobDeviceStatusCollection {
	return o.Payload
}

func (o *JobsGetDevicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobDeviceStatusCollection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
