// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewJobsGetParams creates a new JobsGetParams object
// with the default values initialized.
func NewJobsGetParams() *JobsGetParams {
	var ()
	return &JobsGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJobsGetParamsWithTimeout creates a new JobsGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJobsGetParamsWithTimeout(timeout time.Duration) *JobsGetParams {
	var ()
	return &JobsGetParams{

		timeout: timeout,
	}
}

// NewJobsGetParamsWithContext creates a new JobsGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewJobsGetParamsWithContext(ctx context.Context) *JobsGetParams {
	var ()
	return &JobsGetParams{

		Context: ctx,
	}
}

// NewJobsGetParamsWithHTTPClient creates a new JobsGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewJobsGetParamsWithHTTPClient(client *http.Client) *JobsGetParams {
	var ()
	return &JobsGetParams{
		HTTPClient: client,
	}
}

/*JobsGetParams contains all the parameters to send to the API endpoint
for the jobs get operation typically these are written to a http.Request
*/
type JobsGetParams struct {

	/*JobID
	  Unique ID of the job.

	*/
	JobID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the jobs get params
func (o *JobsGetParams) WithTimeout(timeout time.Duration) *JobsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the jobs get params
func (o *JobsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the jobs get params
func (o *JobsGetParams) WithContext(ctx context.Context) *JobsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the jobs get params
func (o *JobsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the jobs get params
func (o *JobsGetParams) WithHTTPClient(client *http.Client) *JobsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the jobs get params
func (o *JobsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJobID adds the jobID to the jobs get params
func (o *JobsGetParams) WithJobID(jobID string) *JobsGetParams {
	o.SetJobID(jobID)
	return o
}

// SetJobID adds the jobId to the jobs get params
func (o *JobsGetParams) SetJobID(jobID string) {
	o.JobID = jobID
}

// WriteToRequest writes these params to a swagger request
func (o *JobsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param job_id
	if err := r.SetPathParam("job_id", o.JobID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
