// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// JobsSetReader is a Reader for the JobsSet structure.
type JobsSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JobsSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewJobsSetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewJobsSetOK creates a JobsSetOK with default headers values
func NewJobsSetOK() *JobsSetOK {
	return &JobsSetOK{}
}

/*JobsSetOK handles this case with default header values.

Success
*/
type JobsSetOK struct {
	Payload *models.Job
}

func (o *JobsSetOK) Error() string {
	return fmt.Sprintf("[PUT /jobs/{job_id}][%d] jobsSetOK  %+v", 200, o.Payload)
}

func (o *JobsSetOK) GetPayload() *models.Job {
	return o.Payload
}

func (o *JobsSetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Job)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
