// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewJobsListParams creates a new JobsListParams object
// with the default values initialized.
func NewJobsListParams() *JobsListParams {

	return &JobsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJobsListParamsWithTimeout creates a new JobsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJobsListParamsWithTimeout(timeout time.Duration) *JobsListParams {

	return &JobsListParams{

		timeout: timeout,
	}
}

// NewJobsListParamsWithContext creates a new JobsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewJobsListParamsWithContext(ctx context.Context) *JobsListParams {

	return &JobsListParams{

		Context: ctx,
	}
}

// NewJobsListParamsWithHTTPClient creates a new JobsListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewJobsListParamsWithHTTPClient(client *http.Client) *JobsListParams {

	return &JobsListParams{
		HTTPClient: client,
	}
}

/*JobsListParams contains all the parameters to send to the API endpoint
for the jobs list operation typically these are written to a http.Request
*/
type JobsListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the jobs list params
func (o *JobsListParams) WithTimeout(timeout time.Duration) *JobsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the jobs list params
func (o *JobsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the jobs list params
func (o *JobsListParams) WithContext(ctx context.Context) *JobsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the jobs list params
func (o *JobsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the jobs list params
func (o *JobsListParams) WithHTTPClient(client *http.Client) *JobsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the jobs list params
func (o *JobsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *JobsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
