// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRulesGetParams creates a new RulesGetParams object
// with the default values initialized.
func NewRulesGetParams() *RulesGetParams {
	var ()
	return &RulesGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRulesGetParamsWithTimeout creates a new RulesGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRulesGetParamsWithTimeout(timeout time.Duration) *RulesGetParams {
	var ()
	return &RulesGetParams{

		timeout: timeout,
	}
}

// NewRulesGetParamsWithContext creates a new RulesGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewRulesGetParamsWithContext(ctx context.Context) *RulesGetParams {
	var ()
	return &RulesGetParams{

		Context: ctx,
	}
}

// NewRulesGetParamsWithHTTPClient creates a new RulesGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRulesGetParamsWithHTTPClient(client *http.Client) *RulesGetParams {
	var ()
	return &RulesGetParams{
		HTTPClient: client,
	}
}

/*RulesGetParams contains all the parameters to send to the API endpoint
for the rules get operation typically these are written to a http.Request
*/
type RulesGetParams struct {

	/*RuleID
	  Unique ID of the rule.

	*/
	RuleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the rules get params
func (o *RulesGetParams) WithTimeout(timeout time.Duration) *RulesGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rules get params
func (o *RulesGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rules get params
func (o *RulesGetParams) WithContext(ctx context.Context) *RulesGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rules get params
func (o *RulesGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rules get params
func (o *RulesGetParams) WithHTTPClient(client *http.Client) *RulesGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rules get params
func (o *RulesGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRuleID adds the ruleID to the rules get params
func (o *RulesGetParams) WithRuleID(ruleID string) *RulesGetParams {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the rules get params
func (o *RulesGetParams) SetRuleID(ruleID string) {
	o.RuleID = ruleID
}

// WriteToRequest writes these params to a swagger request
func (o *RulesGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param rule_id
	if err := r.SetPathParam("rule_id", o.RuleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
