// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"com.azure.iot/iotcentral/iotcgo/models"
)

// RulesListReader is a Reader for the RulesList structure.
type RulesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RulesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRulesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRulesListOK creates a RulesListOK with default headers values
func NewRulesListOK() *RulesListOK {
	return &RulesListOK{}
}

/*RulesListOK handles this case with default header values.

Success
*/
type RulesListOK struct {
	Payload *models.RuleCollection
}

func (o *RulesListOK) Error() string {
	return fmt.Sprintf("[GET /rules][%d] rulesListOK  %+v", 200, o.Payload)
}

func (o *RulesListOK) GetPayload() *models.RuleCollection {
	return o.Payload
}

func (o *RulesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuleCollection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
