// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UsersRemoveReader is a Reader for the UsersRemove structure.
type UsersRemoveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersRemoveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUsersRemoveNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUsersRemoveNoContent creates a UsersRemoveNoContent with default headers values
func NewUsersRemoveNoContent() *UsersRemoveNoContent {
	return &UsersRemoveNoContent{}
}

/*UsersRemoveNoContent handles this case with default header values.

Success
*/
type UsersRemoveNoContent struct {
}

func (o *UsersRemoveNoContent) Error() string {
	return fmt.Sprintf("[DELETE /users/{user_id}][%d] usersRemoveNoContent ", 204)
}

func (o *UsersRemoveNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
