// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUsersRemoveParams creates a new UsersRemoveParams object
// with the default values initialized.
func NewUsersRemoveParams() *UsersRemoveParams {
	var ()
	return &UsersRemoveParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUsersRemoveParamsWithTimeout creates a new UsersRemoveParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUsersRemoveParamsWithTimeout(timeout time.Duration) *UsersRemoveParams {
	var ()
	return &UsersRemoveParams{

		timeout: timeout,
	}
}

// NewUsersRemoveParamsWithContext creates a new UsersRemoveParams object
// with the default values initialized, and the ability to set a context for a request
func NewUsersRemoveParamsWithContext(ctx context.Context) *UsersRemoveParams {
	var ()
	return &UsersRemoveParams{

		Context: ctx,
	}
}

// NewUsersRemoveParamsWithHTTPClient creates a new UsersRemoveParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUsersRemoveParamsWithHTTPClient(client *http.Client) *UsersRemoveParams {
	var ()
	return &UsersRemoveParams{
		HTTPClient: client,
	}
}

/*UsersRemoveParams contains all the parameters to send to the API endpoint
for the users remove operation typically these are written to a http.Request
*/
type UsersRemoveParams struct {

	/*UserID
	  Unique ID of the user.

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the users remove params
func (o *UsersRemoveParams) WithTimeout(timeout time.Duration) *UsersRemoveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the users remove params
func (o *UsersRemoveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the users remove params
func (o *UsersRemoveParams) WithContext(ctx context.Context) *UsersRemoveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the users remove params
func (o *UsersRemoveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the users remove params
func (o *UsersRemoveParams) WithHTTPClient(client *http.Client) *UsersRemoveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the users remove params
func (o *UsersRemoveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the users remove params
func (o *UsersRemoveParams) WithUserID(userID string) *UsersRemoveParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the users remove params
func (o *UsersRemoveParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UsersRemoveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user_id
	if err := r.SetPathParam("user_id", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
