// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUsersListParams creates a new UsersListParams object
// with the default values initialized.
func NewUsersListParams() *UsersListParams {

	return &UsersListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUsersListParamsWithTimeout creates a new UsersListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUsersListParamsWithTimeout(timeout time.Duration) *UsersListParams {

	return &UsersListParams{

		timeout: timeout,
	}
}

// NewUsersListParamsWithContext creates a new UsersListParams object
// with the default values initialized, and the ability to set a context for a request
func NewUsersListParamsWithContext(ctx context.Context) *UsersListParams {

	return &UsersListParams{

		Context: ctx,
	}
}

// NewUsersListParamsWithHTTPClient creates a new UsersListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUsersListParamsWithHTTPClient(client *http.Client) *UsersListParams {

	return &UsersListParams{
		HTTPClient: client,
	}
}

/*UsersListParams contains all the parameters to send to the API endpoint
for the users list operation typically these are written to a http.Request
*/
type UsersListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the users list params
func (o *UsersListParams) WithTimeout(timeout time.Duration) *UsersListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the users list params
func (o *UsersListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the users list params
func (o *UsersListParams) WithContext(ctx context.Context) *UsersListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the users list params
func (o *UsersListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the users list params
func (o *UsersListParams) WithHTTPClient(client *http.Client) *UsersListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the users list params
func (o *UsersListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *UsersListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
