// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"encoding/json"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ActionCollection action collection
//
// swagger:model ActionCollection
type ActionCollection struct {

	// URL to get the next page of actions.
	NextLink string `json:"nextLink,omitempty"`

	valueField []Action
}

// Value gets the value of this base type
func (m *ActionCollection) Value() []Action {
	return m.valueField
}

// SetValue sets the value of this base type
func (m *ActionCollection) SetValue(val []Action) {
	m.valueField = val
}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *ActionCollection) UnmarshalJSON(raw []byte) error {
	var data struct {
		NextLink string `json:"nextLink,omitempty"`

		Value json.RawMessage `json:"value"`
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	propValue, err := UnmarshalActionSlice(bytes.NewBuffer(data.Value), runtime.JSONConsumer())
	if err != nil && err != io.EOF {
		return err
	}

	var result ActionCollection

	// nextLink
	result.NextLink = data.NextLink

	// value
	result.valueField = propValue

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m ActionCollection) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {
		NextLink string `json:"nextLink,omitempty"`
	}{

		NextLink: m.NextLink,
	})
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		Value []Action `json:"value"`
	}{

		Value: m.valueField,
	})
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this action collection
func (m *ActionCollection) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ActionCollection) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value()); err != nil {
		return err
	}

	for i := 0; i < len(m.Value()); i++ {

		if err := m.valueField[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("value" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ActionCollection) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActionCollection) UnmarshalBinary(b []byte) error {
	var res ActionCollection
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
