// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeviceGroup device group
//
// swagger:model DeviceGroup
type DeviceGroup struct {

	// Display name of the device group.
	DisplayName string `json:"displayName,omitempty"`

	// Unique ID of the device group.
	// Read Only: true
	ID string `json:"id,omitempty"`
}

// Validate validates this device group
func (m *DeviceGroup) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeviceGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceGroup) UnmarshalBinary(b []byte) error {
	var res DeviceGroup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
