// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// JobDeviceStatus job device status
//
// swagger:model JobDeviceStatus
type JobDeviceStatus struct {

	// ID of the device whose job status is being provided.
	// Read Only: true
	ID string `json:"id,omitempty"`

	// Indicates whether the job is starting, running, etc. for the given device.
	// Read Only: true
	Status string `json:"status,omitempty"`
}

// Validate validates this job device status
func (m *JobDeviceStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JobDeviceStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JobDeviceStatus) UnmarshalBinary(b []byte) error {
	var res JobDeviceStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
