// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SymmetricKey symmetric key
//
// swagger:model SymmetricKey
type SymmetricKey struct {

	// The primary key for this credential.
	// Required: true
	PrimaryKey *string `json:"primaryKey"`

	// The secondary key for this credential.
	// Required: true
	SecondaryKey *string `json:"secondaryKey"`
}

// Validate validates this symmetric key
func (m *SymmetricKey) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePrimaryKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSecondaryKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SymmetricKey) validatePrimaryKey(formats strfmt.Registry) error {

	if err := validate.Required("primaryKey", "body", m.PrimaryKey); err != nil {
		return err
	}

	return nil
}

func (m *SymmetricKey) validateSecondaryKey(formats strfmt.Registry) error {

	if err := validate.Required("secondaryKey", "body", m.SecondaryKey); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SymmetricKey) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SymmetricKey) UnmarshalBinary(b []byte) error {
	var res SymmetricKey
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
