// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Tpm tpm
//
// swagger:model Tpm
type Tpm struct {

	// The TPM endorsement key for this credential.
	// Required: true
	EndorsementKey *string `json:"endorsementKey"`
}

// Validate validates this tpm
func (m *Tpm) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEndorsementKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Tpm) validateEndorsementKey(formats strfmt.Registry) error {

	if err := validate.Required("endorsementKey", "body", m.EndorsementKey); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Tpm) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Tpm) UnmarshalBinary(b []byte) error {
	var res Tpm
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
