// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// X509Attestation x509 attestation
//
// swagger:model X509Attestation
type X509Attestation struct {

	// The X.509 credentials for this attestation.
	// Required: true
	X509 *X509 `json:"x509"`
}

// Type gets the type of this subtype
func (m *X509Attestation) Type() string {
	return "X509Attestation"
}

// SetType sets the type of this subtype
func (m *X509Attestation) SetType(val string) {
}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *X509Attestation) UnmarshalJSON(raw []byte) error {
	var data struct {

		// The X.509 credentials for this attestation.
		// Required: true
		X509 *X509 `json:"x509"`
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		Type string `json:"type"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result X509Attestation

	if base.Type != result.Type() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid type value: %q", base.Type)
	}

	result.X509 = data.X509

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m X509Attestation) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {

		// The X.509 credentials for this attestation.
		// Required: true
		X509 *X509 `json:"x509"`
	}{

		X509: m.X509,
	})
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		Type string `json:"type"`
	}{

		Type: m.Type(),
	})
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this x509 attestation
func (m *X509Attestation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateX509(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *X509Attestation) validateX509(formats strfmt.Registry) error {

	if err := validate.Required("x509", "body", m.X509); err != nil {
		return err
	}

	if m.X509 != nil {
		if err := m.X509.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("x509")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *X509Attestation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *X509Attestation) UnmarshalBinary(b []byte) error {
	var res X509Attestation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
