// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// X509CertificateInfo x509 certificate info
//
// swagger:model X509CertificateInfo
type X509CertificateInfo struct {

	// The SHA-1 hash value of the certificate.
	// Required: true
	Sha1Thumbprint *string `json:"sha1Thumbprint"`
}

// Validate validates this x509 certificate info
func (m *X509CertificateInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSha1Thumbprint(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *X509CertificateInfo) validateSha1Thumbprint(formats strfmt.Registry) error {

	if err := validate.Required("sha1Thumbprint", "body", m.Sha1Thumbprint); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *X509CertificateInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *X509CertificateInfo) UnmarshalBinary(b []byte) error {
	var res X509CertificateInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
