// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// X509 x509
//
// swagger:model X509
type X509 struct {

	// The X.509 client certificates for this credential.
	ClientCertificates *X509Certificates `json:"clientCertificates,omitempty"`
}

// Validate validates this x509
func (m *X509) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClientCertificates(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *X509) validateClientCertificates(formats strfmt.Registry) error {

	if swag.IsZero(m.ClientCertificates) { // not required
		return nil
	}

	if m.ClientCertificates != nil {
		if err := m.ClientCertificates.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("clientCertificates")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *X509) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *X509) UnmarshalBinary(b []byte) error {
	var res X509
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
